import type { DashboardPayload, HuntRun } from "../types";

const now = Date.now();
const ago = (minutes: number) => new Date(now - minutes * 60_000).toISOString();

const runs: HuntRun[] = [
  {
    id: "demo-1",
    runNumber: 12,
    source: "issue",
    sourceKey: "BRIAR-12",
    title: "Agent 실행 로그를 작업 상세에 연결",
    stage: "implementing",
    progress: 45,
    detail: "Codex가 이벤트 스트림 어댑터와 회귀 테스트를 작성하고 있습니다.",
    repository: "wordbricks/briar",
    branch: "feat/agent-event-stream",
    commitSha: "8e13ac4",
    startedAt: ago(42),
    updatedAt: ago(2),
    completedAt: null,
    events: [
      {
        id: "event-3",
        stage: "implementing",
        detail: "이벤트 스트림 어댑터 구현 시작",
        actor: "codex",
        occurredAt: ago(23),
      },
      {
        id: "event-2",
        stage: "analyzing",
        detail: "로컬 Git과 Agent 실행 상태 연결 지점 확인",
        actor: "codex",
        occurredAt: ago(36),
      },
      {
        id: "event-1",
        stage: "queued",
        detail: "자동사냥 작업 등록",
        actor: "briar-cli",
        occurredAt: ago(42),
      },
    ],
  },
  {
    id: "demo-2",
    runNumber: 11,
    source: "feedback",
    sourceKey: "feedback-11",
    title: "대시보드 작업 상세 패널 개선",
    stage: "pr_open",
    progress: 65,
    detail: "PR #18의 타입체크와 리뷰 결과를 기다리고 있습니다.",
    repository: "wordbricks/briar",
    branch: "feat/hunt-details",
    commitSha: "c49b012",
    startedAt: ago(108),
    updatedAt: ago(12),
    completedAt: null,
    events: [
      {
        id: "event-6",
        stage: "pr_open",
        detail: "PR #18 생성",
        actor: "codex",
        occurredAt: ago(12),
      },
      {
        id: "event-5",
        stage: "implementing",
        detail: "상세 패널 구현",
        actor: "codex",
        occurredAt: ago(67),
      },
    ],
  },
  {
    id: "demo-3",
    runNumber: 10,
    source: "error",
    sourceKey: "error-10",
    title: "Tauri 시작 시 저장된 세션 복원 실패",
    stage: "blocked",
    progress: 50,
    detail: "Google OAuth 클라이언트 자격증명 등록이 필요합니다.",
    repository: "wordbricks/briar",
    branch: "fix/session-restore",
    commitSha: null,
    startedAt: ago(184),
    updatedAt: ago(31),
    completedAt: null,
    events: [
      {
        id: "event-8",
        stage: "blocked",
        detail: "Google OAuth 자격증명 대기",
        actor: "codex",
        occurredAt: ago(31),
      },
    ],
  },
  {
    id: "demo-4",
    runNumber: 9,
    source: "issue",
    sourceKey: "BRIAR-9",
    title: "D1 작업 이벤트 스키마 추가",
    stage: "completed",
    progress: 100,
    detail: "마이그레이션과 API 검증이 완료되었습니다.",
    repository: "wordbricks/briar",
    branch: "feat/hunt-schema",
    commitSha: "2d0f9a1",
    startedAt: ago(940),
    updatedAt: ago(510),
    completedAt: ago(510),
    events: [
      {
        id: "event-9",
        stage: "completed",
        detail: "Production QA 완료",
        actor: "codex",
        occurredAt: ago(510),
      },
    ],
  },
];

export const demoDashboard: DashboardPayload = {
  project: {
    id: "demo-project",
    name: "Briar",
    repositoryPath: "/Users/jay/git/briar",
    createdAt: ago(3_000),
  },
  runs,
  generatedAt: new Date().toISOString(),
};
