export type DevicePageClient = "desktop" | "mobile" | "web";

const clientCopy = {
  desktop: {
    eyebrow: "DEVICE AUTHORIZATION",
    title: "데스크톱 연결 승인",
    description: "이메일 인증코드 또는 Google로 로그인한 뒤 Briar 데스크톱의 접근을 승인하세요.",
    approve: "이 기기 승인하기",
  },
  mobile: {
    eyebrow: "MOBILE COMPANION",
    title: "Companion 로그인 승인",
    description: "이메일 인증코드 또는 Google로 로그인한 뒤 이 기기의 Briar Companion 로그인을 승인하세요.",
    approve: "이 기기에서 로그인하기",
  },
  web: {
    eyebrow: "BRIAR FOR WEB",
    title: "웹 로그인 승인",
    description: "이메일 인증코드 또는 Google로 로그인한 뒤 열려 있는 Briar 웹 로그인을 승인하세요.",
    approve: "웹에서 로그인하기",
  },
} as const;

export function devicePage(apiOrigin: string, client: DevicePageClient) {
  const copy = clientCopy[client];
  const mobileCompanion = client === "mobile";
  const webApp = client === "web";
  return new Response(
    `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="icon" type="image/png" href="/brand/briar-icon.png"><title>Briar 로그인</title><style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;padding:24px 0;display:grid;place-items:center;background:#08090b;color:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.card{width:min(420px,calc(100vw - 32px));padding:30px;border:1px solid #282a30;border-radius:18px;background:#111318;box-shadow:0 30px 100px #0008}.brand{display:flex;align-items:center;gap:10px;font-weight:750;font-size:20px}.brand img{width:26px;height:26px;display:block;border-radius:6px}.eyebrow{margin-top:32px;color:#9c88ee;font:600 10px ui-monospace,monospace;letter-spacing:1px}h1{margin:10px 0 0;font-size:25px}.code{margin:18px 0;padding:15px;border:1px solid #3f365d;border-radius:10px;background:#171420;text-align:center;font:600 26px ui-monospace,monospace;letter-spacing:4px}.copy{color:#9a9eaa;font-size:13px;line-height:1.6}.auth{display:grid;gap:12px;margin-top:22px}.field{display:grid;gap:7px}.field label{color:#c6c8cf;font-size:12px;font-weight:650}.field input{width:100%;height:44px;padding:0 13px;border:1px solid #34363d;border-radius:9px;background:#17191f;color:#f4f4f5;font:500 15px inherit;outline:none}.field input:focus{border-color:#8b70dd;box-shadow:0 0 0 3px #8b70dd22}.otp-input{text-align:center;font:650 23px ui-monospace,monospace!important;letter-spacing:8px}.actions{display:grid;gap:8px}button{min-height:42px;padding:0 14px;border:1px solid #d8d9de;border-radius:9px;background:#f4f4f5;color:#18191d;font-weight:700;cursor:pointer}button:hover:not(:disabled){filter:brightness(.94)}button:disabled{cursor:not-allowed;opacity:.55}button.secondary{border-color:#34363d;background:#191b20;color:#d5d6da}.row{display:flex;gap:8px}.row button{flex:1}.link{min-height:32px;border:0;background:transparent;color:#a995ef;font-size:12px}.divider{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:10px;color:#9296a1;font-size:11px}.divider:before,.divider:after{content:"";height:1px;background:#2b2d33}.hint{margin:0;color:#858995;font-size:12px;line-height:1.5;text-align:center}.status{min-height:20px;margin-top:14px;color:#9296a1;font-size:12px;line-height:1.45;text-align:center}.status.error{color:#ff9494}.status.success{color:#9bdda9}[hidden]{display:none!important}
</style></head>
<body><main class="card"><div class="brand"><img src="/brand/briar-icon.png" alt="">briar</div><p class="eyebrow">${copy.eyebrow}</p><h1>${copy.title}</h1><p class="copy">${copy.description}</p><div class="code" id="device-code">--------</div>
<section class="auth" id="auth-methods">
  <form class="actions" id="email-form"><div class="field"><label for="email" id="email-label">이메일</label><input id="email" name="email" type="email" autocomplete="email" required placeholder="name@example.com"></div><button id="send-code" type="submit">인증코드 받기</button></form>
  <form class="actions" id="otp-form" hidden><p class="hint" id="sent-copy"></p><div class="field"><label for="otp" id="otp-label">6자리 인증코드</label><input class="otp-input" id="otp" name="otp" type="text" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required></div><button id="verify-code" type="submit">확인하고 계속</button><div class="row"><button class="secondary" id="resend" type="button">인증코드 다시 받기</button><button class="link" id="edit-email" type="button">이메일 수정</button></div></form>
  <div class="divider" id="divider"><span>또는</span></div><button class="secondary" id="google" type="button">Google로 계속</button>
</section>
<section class="actions" id="approval" hidden><button id="approve">${copy.approve}</button><button id="deny" class="secondary">거절</button></section><div class="status" id="status" role="status" aria-live="polite"></div></main>
<script>
const base=${JSON.stringify(apiOrigin)};const mobileCompanion=${JSON.stringify(mobileCompanion)};const webApp=${JSON.stringify(webApp)};const returnUrl='briar-companion://auth-complete';const params=new URLSearchParams(location.search);const switchAccount=params.get('switch_account')==='1';const method=params.get('method');const requestedLocale=params.get('locale');const browserLocale=(navigator.language||'en').toLowerCase();const locale=requestedLocale==='ko'||requestedLocale==='en'||requestedLocale==='zh'?requestedLocale:browserLocale.startsWith('ko')?'ko':browserLocale.startsWith('zh')?'zh':'en';document.documentElement.lang=locale;
const messages={ko:{email:'이메일',send:'인증코드 받기',sending:'인증코드를 보내는 중…',otp:'6자리 인증코드',verify:'확인하고 계속',verifying:'인증코드를 확인하는 중…',sent:'입력한 이메일로 인증코드를 보냈습니다. 메일함과 스팸함을 확인하세요.',resend:'인증코드 다시 받기',resendIn:'{seconds}초 후 다시 받기',edit:'이메일 수정',or:'또는',google:'Google로 계속',openingGoogle:'Google 로그인 페이지를 여는 중…',invalidDevice:'유효한 기기 코드가 없습니다.',choose:'다른 계정으로 로그인할 방법을 선택하세요.',connect:'{email} 계정으로 연결합니다.',failed:'요청에 실패했습니다.',invalidOtp:'인증코드가 올바르지 않습니다.',expired:'인증코드가 만료되었습니다. 새 코드를 받아 주세요.',attempts:'입력 횟수를 초과했습니다. 새 코드를 받아 주세요.',limited:'요청이 너무 많습니다. {seconds}초 후 다시 시도하세요.',approvedMobile:'승인되었습니다. Briar Companion으로 돌아갑니다…',approvedWeb:'승인되었습니다. Briar 웹 탭으로 돌아가세요.',approvedDesktop:'승인되었습니다. Briar 앱으로 돌아가세요.',denied:'요청을 거절했습니다.'},en:{email:'Email',send:'Send sign-in code',sending:'Sending your code…',otp:'6-digit sign-in code',verify:'Verify and continue',verifying:'Checking your code…',sent:'We sent a sign-in code to that email. Check your inbox and spam folder.',resend:'Resend code',resendIn:'Resend in {seconds}s',edit:'Edit email',or:'or',google:'Continue with Google',openingGoogle:'Opening Google sign-in…',invalidDevice:'This device code is not valid.',choose:'Choose how to sign in with another account.',connect:'Connecting {email}.',failed:'The request failed.',invalidOtp:'That sign-in code is not correct.',expired:'That code has expired. Request a new one.',attempts:'Too many attempts. Request a new code.',limited:'Too many requests. Try again in {seconds}s.',approvedMobile:'Approved. Returning to Briar Companion…',approvedWeb:'Approved. Return to your Briar web tab.',approvedDesktop:'Approved. Return to the Briar app.',denied:'The request was denied.'},zh:{email:'邮箱',send:'获取验证码',sending:'正在发送验证码…',otp:'6 位验证码',verify:'验证并继续',verifying:'正在验证…',sent:'验证码已发送至该邮箱，请检查收件箱和垃圾邮件。',resend:'重新发送验证码',resendIn:'{seconds} 秒后可重新发送',edit:'修改邮箱',or:'或',google:'使用 Google 继续',openingGoogle:'正在打开 Google 登录…',invalidDevice:'设备验证码无效。',choose:'请选择其他账号的登录方式。',connect:'正在连接 {email}。',failed:'请求失败。',invalidOtp:'验证码不正确。',expired:'验证码已过期，请获取新验证码。',attempts:'尝试次数过多，请获取新验证码。',limited:'请求过于频繁，请在 {seconds} 秒后重试。',approvedMobile:'已批准，正在返回 Briar Companion…',approvedWeb:'已批准，请返回 Briar 网页标签页。',approvedDesktop:'已批准，请返回 Briar 应用。',denied:'已拒绝该请求。'}};const m=messages[locale];const format=(value,variables={})=>value.replace(/\\{(\\w+)\\}/g,(_,key)=>String(variables[key]??''));
const code=(params.get('user_code')||'').replace(/-/g,'').toUpperCase();const callbackParams=new URLSearchParams({user_code:code,locale});if(mobileCompanion)callbackParams.set('client','mobile');if(webApp)callbackParams.set('client','web');const callbackUrl=base+'/device?'+callbackParams.toString();const deviceCode=document.querySelector('#device-code');const methods=document.querySelector('#auth-methods');const approval=document.querySelector('#approval');const status=document.querySelector('#status');const emailForm=document.querySelector('#email-form');const otpForm=document.querySelector('#otp-form');const emailInput=document.querySelector('#email');const otpInput=document.querySelector('#otp');const sendButton=document.querySelector('#send-code');const verifyButton=document.querySelector('#verify-code');const resendButton=document.querySelector('#resend');const editEmail=document.querySelector('#edit-email');const google=document.querySelector('#google');const approve=document.querySelector('#approve');const deny=document.querySelector('#deny');const sentCopy=document.querySelector('#sent-copy');let activeEmail='';let countdown=0;let countdownTimer=null;
document.querySelector('#email-label').textContent=m.email;sendButton.textContent=m.send;document.querySelector('#otp-label').textContent=m.otp;verifyButton.textContent=m.verify;resendButton.textContent=m.resend;editEmail.textContent=m.edit;document.querySelector('#divider span').textContent=m.or;google.textContent=m.google;deviceCode.textContent=code||'--------';
function setStatus(message='',kind=''){status.textContent=message;status.className='status'+(kind?' '+kind:'')}
async function api(path,options={}){const headers=new Headers(options.headers||{});headers.set('content-type','application/json');headers.set('x-briar-locale',locale);const response=await fetch(base+'/api/auth'+path,{credentials:'include',...options,headers});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.message||data.error_description||m.failed);error.code=data.code;error.status=response.status;error.retryAfter=Number(response.headers.get('Retry-After')||response.headers.get('X-Retry-After')||0);throw error}return data}
function errorMessage(error){if(error.status===429)return format(m.limited,{seconds:Math.max(1,error.retryAfter||60)});if(error.code==='OTP_EXPIRED')return m.expired;if(error.code==='TOO_MANY_ATTEMPTS')return m.attempts;if(error.code==='INVALID_OTP')return m.invalidOtp;return error.message||m.failed}
function renderCountdown(){if(countdown>0){resendButton.disabled=true;resendButton.textContent=format(m.resendIn,{seconds:countdown});if(!emailForm.hidden){sendButton.disabled=true;sendButton.textContent=format(m.resendIn,{seconds:countdown})}}else{resendButton.disabled=false;resendButton.textContent=m.resend;sendButton.disabled=false;sendButton.textContent=m.send}}
function startCountdown(seconds){countdown=Math.max(0,Math.ceil(seconds));if(countdownTimer)clearInterval(countdownTimer);renderCountdown();countdownTimer=setInterval(()=>{countdown=Math.max(0,countdown-1);renderCountdown();if(countdown===0){clearInterval(countdownTimer);countdownTimer=null}},1000)}
function resetCountdown(){if(countdownTimer)clearInterval(countdownTimer);countdownTimer=null;countdown=0;renderCountdown()}
function showEmail(){emailForm.hidden=false;otpForm.hidden=true;emailInput.focus();setStatus(switchAccount?m.choose:'')}
function showOtp(){emailForm.hidden=true;otpForm.hidden=false;sentCopy.textContent=m.sent;otpInput.value='';otpInput.focus()}
async function sendCode(){activeEmail=emailInput.value.trim().toLowerCase();sendButton.disabled=true;sendButton.textContent=m.sending;if(!otpForm.hidden){resendButton.disabled=true;resendButton.textContent=m.sending}setStatus(m.sending);try{await api('/email-otp/send-verification-otp',{method:'POST',body:JSON.stringify({email:activeEmail,type:'sign-in'})});showOtp();startCountdown(60);setStatus(m.sent,'success')}catch(error){const retry=Math.max(0,error.retryAfter||0);if(retry)startCountdown(retry);setStatus(errorMessage(error),'error')}finally{if(countdown===0)renderCountdown()}}
async function verifyCode(){const otp=otpInput.value.replace(/\\D/g,'').slice(0,6);otpInput.value=otp;if(otp.length!==6){setStatus(m.invalidOtp,'error');return}verifyButton.disabled=true;verifyButton.textContent=m.verifying;setStatus(m.verifying);try{const localName=activeEmail.split('@')[0]||activeEmail;const result=await api('/sign-in/email-otp',{method:'POST',body:JSON.stringify({email:activeEmail,otp,name:localName})});await connect(result.user)}catch(error){setStatus(errorMessage(error),'error')}finally{verifyButton.disabled=false;verifyButton.textContent=m.verify}}
async function beginGoogle(){google.disabled=true;setStatus(m.openingGoogle);try{const data=await api('/sign-in/social',{method:'POST',body:JSON.stringify({provider:'google',callbackURL:callbackUrl,...(switchAccount?{additionalParams:{prompt:'select_account'}}:{})})});location.href=data.url}catch(error){google.disabled=false;setStatus(errorMessage(error),'error')}}
async function connect(user){methods.hidden=true;await api('/device?user_code='+encodeURIComponent(code));approval.hidden=false;setStatus(format(m.connect,{email:user.email}),'success')}
emailForm.onsubmit=(event)=>{event.preventDefault();if(emailInput.reportValidity())void sendCode()};otpForm.onsubmit=(event)=>{event.preventDefault();void verifyCode()};emailInput.oninput=()=>{if(countdown>0&&emailInput.value.trim().toLowerCase()!==activeEmail)resetCountdown()};otpInput.oninput=()=>{otpInput.value=otpInput.value.replace(/\\D/g,'').slice(0,6)};resendButton.onclick=()=>{if(countdown===0)void sendCode()};editEmail.onclick=()=>{activeEmail='';resetCountdown();showEmail()};google.onclick=()=>void beginGoogle();
approve.onclick=async()=>{try{await api('/device/approve',{method:'POST',body:JSON.stringify({userCode:code})});approval.hidden=true;if(mobileCompanion){setStatus(m.approvedMobile,'success');window.setTimeout(()=>location.replace(returnUrl),250)}else if(webApp){setStatus(m.approvedWeb,'success');window.setTimeout(()=>window.close(),800)}else setStatus(m.approvedDesktop,'success')}catch(error){setStatus(errorMessage(error),'error')}};deny.onclick=async()=>{try{await api('/device/deny',{method:'POST',body:JSON.stringify({userCode:code})});approval.hidden=true;setStatus(m.denied)}catch(error){setStatus(errorMessage(error),'error')}};
async function boot(){if(!code){methods.hidden=true;setStatus(m.invalidDevice,'error');return}if(switchAccount){showEmail();return}const session=await api('/get-session').catch(()=>null);if(session?.user){await connect(session.user);return}if(method==='google'){await beginGoogle();return}showEmail()}void boot();
</script></body></html>`,
    {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Referrer-Policy": "no-referrer",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
      },
    },
  );
}
