// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/account.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol BriarAPI_AccountServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `getCurrentUser`(request: BriarAPI_GetCurrentUserRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetCurrentUserResponse>

    @available(iOS 13, *)
    func `registerMobilePushDevice`(request: BriarAPI_RegisterMobilePushDeviceRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_RegisterMobilePushDeviceResponse>

    @available(iOS 13, *)
    func `unregisterMobilePushDevice`(request: BriarAPI_UnregisterMobilePushDeviceRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UnregisterMobilePushDeviceResponse>
}

/// Concrete implementation of `BriarAPI_AccountServiceClientInterface`.
public final class BriarAPI_AccountServiceClient: BriarAPI_AccountServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `getCurrentUser`(request: BriarAPI_GetCurrentUserRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetCurrentUserResponse> {
        return await self.client.unary(path: "/briar.app.v1.AccountService/GetCurrentUser", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `registerMobilePushDevice`(request: BriarAPI_RegisterMobilePushDeviceRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_RegisterMobilePushDeviceResponse> {
        return await self.client.unary(path: "/briar.app.v1.AccountService/RegisterMobilePushDevice", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `unregisterMobilePushDevice`(request: BriarAPI_UnregisterMobilePushDeviceRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UnregisterMobilePushDeviceResponse> {
        return await self.client.unary(path: "/briar.app.v1.AccountService/UnregisterMobilePushDevice", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let getCurrentUser = Connect.MethodSpec(name: "GetCurrentUser", service: "briar.app.v1.AccountService", type: .unary)
            public static let registerMobilePushDevice = Connect.MethodSpec(name: "RegisterMobilePushDevice", service: "briar.app.v1.AccountService", type: .unary)
            public static let unregisterMobilePushDevice = Connect.MethodSpec(name: "UnregisterMobilePushDevice", service: "briar.app.v1.AccountService", type: .unary)
        }
    }
}
