// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/agent.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol BriarAPI_AgentServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `listWorkspaceAgents`(request: BriarAPI_ListWorkspaceAgentsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListWorkspaceAgentsResponse>

    @available(iOS 13, *)
    func `createWorkspaceAgent`(request: BriarAPI_CreateWorkspaceAgentRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateWorkspaceAgentResponse>

    @available(iOS 13, *)
    func `updateWorkspaceAgent`(request: BriarAPI_UpdateWorkspaceAgentRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateWorkspaceAgentResponse>

    @available(iOS 13, *)
    func `deleteWorkspaceAgent`(request: BriarAPI_DeleteWorkspaceAgentRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_DeleteWorkspaceAgentResponse>

    @available(iOS 13, *)
    func `listProjectAgents`(request: BriarAPI_ListProjectAgentsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListProjectAgentsResponse>

    @available(iOS 13, *)
    func `createProjectAgent`(request: BriarAPI_CreateProjectAgentRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateProjectAgentResponse>

    @available(iOS 13, *)
    func `updateProjectAgent`(request: BriarAPI_UpdateProjectAgentRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateProjectAgentResponse>

    @available(iOS 13, *)
    func `deleteProjectAgent`(request: BriarAPI_DeleteProjectAgentRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_DeleteProjectAgentResponse>

    @available(iOS 13, *)
    func `listProjectAgentSchedules`(request: BriarAPI_ListProjectAgentSchedulesRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListProjectAgentSchedulesResponse>

    @available(iOS 13, *)
    func `createProjectAgentSchedule`(request: BriarAPI_CreateProjectAgentScheduleRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateProjectAgentScheduleResponse>

    @available(iOS 13, *)
    func `updateProjectAgentSchedule`(request: BriarAPI_UpdateProjectAgentScheduleRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateProjectAgentScheduleResponse>

    @available(iOS 13, *)
    func `deleteProjectAgentSchedule`(request: BriarAPI_DeleteProjectAgentScheduleRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_DeleteProjectAgentScheduleResponse>

    @available(iOS 13, *)
    func `listProjectAgentScheduleRuns`(request: BriarAPI_ListProjectAgentScheduleRunsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListProjectAgentScheduleRunsResponse>

    @available(iOS 13, *)
    func `claimProjectAgentScheduleRun`(request: BriarAPI_ClaimProjectAgentScheduleRunRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ClaimProjectAgentScheduleRunResponse>

    @available(iOS 13, *)
    func `completeProjectAgentScheduleRun`(request: BriarAPI_CompleteProjectAgentScheduleRunRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CompleteProjectAgentScheduleRunResponse>

    @available(iOS 13, *)
    func `renewProjectAgentScheduleRun`(request: BriarAPI_RenewProjectAgentScheduleRunRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_RenewProjectAgentScheduleRunResponse>

    @available(iOS 13, *)
    func `listProjectAgentSessions`(request: BriarAPI_ListProjectAgentSessionsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListProjectAgentSessionsResponse>

    @available(iOS 13, *)
    func `syncProjectAgentSessions`(request: BriarAPI_SyncProjectAgentSessionsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_SyncProjectAgentSessionsResponse>

    @available(iOS 13, *)
    func `getProjectAgentSession`(request: BriarAPI_GetProjectAgentSessionRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetProjectAgentSessionResponse>

    @available(iOS 13, *)
    func `putProjectAgentSession`(request: BriarAPI_PutProjectAgentSessionRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_PutProjectAgentSessionResponse>

    @available(iOS 13, *)
    func `runProjectAgentTask`(request: BriarAPI_RunProjectAgentTaskRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_RunProjectAgentTaskResponse>

    @available(iOS 13, *)
    func `cancelProjectAgentTask`(request: BriarAPI_CancelProjectAgentTaskRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CancelProjectAgentTaskResponse>

    @available(iOS 13, *)
    func `getProjectAgentTranscript`(request: BriarAPI_GetProjectAgentTranscriptRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetProjectAgentTranscriptResponse>

    @available(iOS 13, *)
    func `listProjectAgentTranscriptSessions`(request: BriarAPI_ListProjectAgentTranscriptSessionsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListProjectAgentTranscriptSessionsResponse>
}

/// Concrete implementation of `BriarAPI_AgentServiceClientInterface`.
public final class BriarAPI_AgentServiceClient: BriarAPI_AgentServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `listWorkspaceAgents`(request: BriarAPI_ListWorkspaceAgentsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListWorkspaceAgentsResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/ListWorkspaceAgents", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createWorkspaceAgent`(request: BriarAPI_CreateWorkspaceAgentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateWorkspaceAgentResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/CreateWorkspaceAgent", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateWorkspaceAgent`(request: BriarAPI_UpdateWorkspaceAgentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateWorkspaceAgentResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/UpdateWorkspaceAgent", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `deleteWorkspaceAgent`(request: BriarAPI_DeleteWorkspaceAgentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteWorkspaceAgentResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/DeleteWorkspaceAgent", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listProjectAgents`(request: BriarAPI_ListProjectAgentsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListProjectAgentsResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/ListProjectAgents", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createProjectAgent`(request: BriarAPI_CreateProjectAgentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateProjectAgentResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/CreateProjectAgent", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateProjectAgent`(request: BriarAPI_UpdateProjectAgentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateProjectAgentResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/UpdateProjectAgent", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `deleteProjectAgent`(request: BriarAPI_DeleteProjectAgentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteProjectAgentResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/DeleteProjectAgent", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listProjectAgentSchedules`(request: BriarAPI_ListProjectAgentSchedulesRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListProjectAgentSchedulesResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/ListProjectAgentSchedules", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createProjectAgentSchedule`(request: BriarAPI_CreateProjectAgentScheduleRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateProjectAgentScheduleResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/CreateProjectAgentSchedule", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateProjectAgentSchedule`(request: BriarAPI_UpdateProjectAgentScheduleRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateProjectAgentScheduleResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/UpdateProjectAgentSchedule", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `deleteProjectAgentSchedule`(request: BriarAPI_DeleteProjectAgentScheduleRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteProjectAgentScheduleResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/DeleteProjectAgentSchedule", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listProjectAgentScheduleRuns`(request: BriarAPI_ListProjectAgentScheduleRunsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListProjectAgentScheduleRunsResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/ListProjectAgentScheduleRuns", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `claimProjectAgentScheduleRun`(request: BriarAPI_ClaimProjectAgentScheduleRunRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ClaimProjectAgentScheduleRunResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/ClaimProjectAgentScheduleRun", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `completeProjectAgentScheduleRun`(request: BriarAPI_CompleteProjectAgentScheduleRunRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CompleteProjectAgentScheduleRunResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/CompleteProjectAgentScheduleRun", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `renewProjectAgentScheduleRun`(request: BriarAPI_RenewProjectAgentScheduleRunRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_RenewProjectAgentScheduleRunResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/RenewProjectAgentScheduleRun", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listProjectAgentSessions`(request: BriarAPI_ListProjectAgentSessionsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListProjectAgentSessionsResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/ListProjectAgentSessions", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `syncProjectAgentSessions`(request: BriarAPI_SyncProjectAgentSessionsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_SyncProjectAgentSessionsResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/SyncProjectAgentSessions", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getProjectAgentSession`(request: BriarAPI_GetProjectAgentSessionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetProjectAgentSessionResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/GetProjectAgentSession", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `putProjectAgentSession`(request: BriarAPI_PutProjectAgentSessionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_PutProjectAgentSessionResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/PutProjectAgentSession", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `runProjectAgentTask`(request: BriarAPI_RunProjectAgentTaskRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_RunProjectAgentTaskResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/RunProjectAgentTask", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `cancelProjectAgentTask`(request: BriarAPI_CancelProjectAgentTaskRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CancelProjectAgentTaskResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/CancelProjectAgentTask", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getProjectAgentTranscript`(request: BriarAPI_GetProjectAgentTranscriptRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetProjectAgentTranscriptResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/GetProjectAgentTranscript", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listProjectAgentTranscriptSessions`(request: BriarAPI_ListProjectAgentTranscriptSessionsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListProjectAgentTranscriptSessionsResponse> {
        return await self.client.unary(path: "/briar.app.v1.AgentService/ListProjectAgentTranscriptSessions", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let listWorkspaceAgents = Connect.MethodSpec(name: "ListWorkspaceAgents", service: "briar.app.v1.AgentService", type: .unary)
            public static let createWorkspaceAgent = Connect.MethodSpec(name: "CreateWorkspaceAgent", service: "briar.app.v1.AgentService", type: .unary)
            public static let updateWorkspaceAgent = Connect.MethodSpec(name: "UpdateWorkspaceAgent", service: "briar.app.v1.AgentService", type: .unary)
            public static let deleteWorkspaceAgent = Connect.MethodSpec(name: "DeleteWorkspaceAgent", service: "briar.app.v1.AgentService", type: .unary)
            public static let listProjectAgents = Connect.MethodSpec(name: "ListProjectAgents", service: "briar.app.v1.AgentService", type: .unary)
            public static let createProjectAgent = Connect.MethodSpec(name: "CreateProjectAgent", service: "briar.app.v1.AgentService", type: .unary)
            public static let updateProjectAgent = Connect.MethodSpec(name: "UpdateProjectAgent", service: "briar.app.v1.AgentService", type: .unary)
            public static let deleteProjectAgent = Connect.MethodSpec(name: "DeleteProjectAgent", service: "briar.app.v1.AgentService", type: .unary)
            public static let listProjectAgentSchedules = Connect.MethodSpec(name: "ListProjectAgentSchedules", service: "briar.app.v1.AgentService", type: .unary)
            public static let createProjectAgentSchedule = Connect.MethodSpec(name: "CreateProjectAgentSchedule", service: "briar.app.v1.AgentService", type: .unary)
            public static let updateProjectAgentSchedule = Connect.MethodSpec(name: "UpdateProjectAgentSchedule", service: "briar.app.v1.AgentService", type: .unary)
            public static let deleteProjectAgentSchedule = Connect.MethodSpec(name: "DeleteProjectAgentSchedule", service: "briar.app.v1.AgentService", type: .unary)
            public static let listProjectAgentScheduleRuns = Connect.MethodSpec(name: "ListProjectAgentScheduleRuns", service: "briar.app.v1.AgentService", type: .unary)
            public static let claimProjectAgentScheduleRun = Connect.MethodSpec(name: "ClaimProjectAgentScheduleRun", service: "briar.app.v1.AgentService", type: .unary)
            public static let completeProjectAgentScheduleRun = Connect.MethodSpec(name: "CompleteProjectAgentScheduleRun", service: "briar.app.v1.AgentService", type: .unary)
            public static let renewProjectAgentScheduleRun = Connect.MethodSpec(name: "RenewProjectAgentScheduleRun", service: "briar.app.v1.AgentService", type: .unary)
            public static let listProjectAgentSessions = Connect.MethodSpec(name: "ListProjectAgentSessions", service: "briar.app.v1.AgentService", type: .unary)
            public static let syncProjectAgentSessions = Connect.MethodSpec(name: "SyncProjectAgentSessions", service: "briar.app.v1.AgentService", type: .unary)
            public static let getProjectAgentSession = Connect.MethodSpec(name: "GetProjectAgentSession", service: "briar.app.v1.AgentService", type: .unary)
            public static let putProjectAgentSession = Connect.MethodSpec(name: "PutProjectAgentSession", service: "briar.app.v1.AgentService", type: .unary)
            public static let runProjectAgentTask = Connect.MethodSpec(name: "RunProjectAgentTask", service: "briar.app.v1.AgentService", type: .unary)
            public static let cancelProjectAgentTask = Connect.MethodSpec(name: "CancelProjectAgentTask", service: "briar.app.v1.AgentService", type: .unary)
            public static let getProjectAgentTranscript = Connect.MethodSpec(name: "GetProjectAgentTranscript", service: "briar.app.v1.AgentService", type: .unary)
            public static let listProjectAgentTranscriptSessions = Connect.MethodSpec(name: "ListProjectAgentTranscriptSessions", service: "briar.app.v1.AgentService", type: .unary)
        }
    }
}
