// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/dm_memory.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol BriarAPI_DmMemoryServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `listDmMemories`(request: BriarAPI_ListDmMemoriesRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListDmMemoriesResponse>

    @available(iOS 13, *)
    func `getDmMemoryDocument`(request: BriarAPI_GetDmMemoryDocumentRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetDmMemoryDocumentResponse>

    @available(iOS 13, *)
    func `createDmMemoryDocument`(request: BriarAPI_CreateDmMemoryDocumentRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateDmMemoryDocumentResponse>

    @available(iOS 13, *)
    func `updateDmMemoryDocument`(request: BriarAPI_UpdateDmMemoryDocumentRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateDmMemoryDocumentResponse>

    @available(iOS 13, *)
    func `deleteDmMemoryDocument`(request: BriarAPI_DeleteDmMemoryDocumentRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_DeleteDmMemoryDocumentResponse>

    @available(iOS 13, *)
    func `updateDmMemorySettings`(request: BriarAPI_UpdateDmMemorySettingsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateDmMemorySettingsResponse>
}

/// Concrete implementation of `BriarAPI_DmMemoryServiceClientInterface`.
public final class BriarAPI_DmMemoryServiceClient: BriarAPI_DmMemoryServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `listDmMemories`(request: BriarAPI_ListDmMemoriesRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListDmMemoriesResponse> {
        return await self.client.unary(path: "/briar.app.v1.DmMemoryService/ListDmMemories", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getDmMemoryDocument`(request: BriarAPI_GetDmMemoryDocumentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetDmMemoryDocumentResponse> {
        return await self.client.unary(path: "/briar.app.v1.DmMemoryService/GetDmMemoryDocument", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createDmMemoryDocument`(request: BriarAPI_CreateDmMemoryDocumentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateDmMemoryDocumentResponse> {
        return await self.client.unary(path: "/briar.app.v1.DmMemoryService/CreateDmMemoryDocument", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateDmMemoryDocument`(request: BriarAPI_UpdateDmMemoryDocumentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateDmMemoryDocumentResponse> {
        return await self.client.unary(path: "/briar.app.v1.DmMemoryService/UpdateDmMemoryDocument", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `deleteDmMemoryDocument`(request: BriarAPI_DeleteDmMemoryDocumentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteDmMemoryDocumentResponse> {
        return await self.client.unary(path: "/briar.app.v1.DmMemoryService/DeleteDmMemoryDocument", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateDmMemorySettings`(request: BriarAPI_UpdateDmMemorySettingsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateDmMemorySettingsResponse> {
        return await self.client.unary(path: "/briar.app.v1.DmMemoryService/UpdateDmMemorySettings", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let listDmMemories = Connect.MethodSpec(name: "ListDmMemories", service: "briar.app.v1.DmMemoryService", type: .unary)
            public static let getDmMemoryDocument = Connect.MethodSpec(name: "GetDmMemoryDocument", service: "briar.app.v1.DmMemoryService", type: .unary)
            public static let createDmMemoryDocument = Connect.MethodSpec(name: "CreateDmMemoryDocument", service: "briar.app.v1.DmMemoryService", type: .unary)
            public static let updateDmMemoryDocument = Connect.MethodSpec(name: "UpdateDmMemoryDocument", service: "briar.app.v1.DmMemoryService", type: .unary)
            public static let deleteDmMemoryDocument = Connect.MethodSpec(name: "DeleteDmMemoryDocument", service: "briar.app.v1.DmMemoryService", type: .unary)
            public static let updateDmMemorySettings = Connect.MethodSpec(name: "UpdateDmMemorySettings", service: "briar.app.v1.DmMemoryService", type: .unary)
        }
    }
}
