// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/fleet.proto
//

import Connect
import Foundation
import SwiftProtobuf

/// FleetService owns authenticated organization-level machine administration.
/// WebSocket upgrades for remote desktop and guided setup remain ordinary HTTP;
/// this service owns only their unary control-plane requests and tickets.
public protocol BriarAPI_FleetServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `registerProjectExecutionWorker`(request: BriarAPI_RegisterProjectExecutionWorkerRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_RegisterProjectExecutionWorkerResponse>

    @available(iOS 13, *)
    func `bindProjectExecutionWorker`(request: BriarAPI_BindProjectExecutionWorkerRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_BindProjectExecutionWorkerResponse>

    @available(iOS 13, *)
    func `unbindProjectExecutionWorker`(request: BriarAPI_UnbindProjectExecutionWorkerRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UnbindProjectExecutionWorkerResponse>

    @available(iOS 13, *)
    func `listExecutionWorkers`(request: BriarAPI_ListExecutionWorkersRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListExecutionWorkersResponse>

    @available(iOS 13, *)
    func `requestExecutionWorkerUpdate`(request: BriarAPI_RequestExecutionWorkerUpdateRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_RequestExecutionWorkerUpdateResponse>

    @available(iOS 13, *)
    func `updateExecutionWorker`(request: BriarAPI_UpdateExecutionWorkerRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateExecutionWorkerResponse>

    @available(iOS 13, *)
    func `deleteExecutionWorker`(request: BriarAPI_DeleteExecutionWorkerRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_DeleteExecutionWorkerResponse>

    @available(iOS 13, *)
    func `getManagedComputerProduct`(request: BriarAPI_GetManagedComputerProductRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetManagedComputerProductResponse>

    @available(iOS 13, *)
    func `listManagedComputers`(request: BriarAPI_ListManagedComputersRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListManagedComputersResponse>

    @available(iOS 13, *)
    func `getManagedComputer`(request: BriarAPI_GetManagedComputerRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetManagedComputerResponse>

    @available(iOS 13, *)
    func `validateManagedComputerPromotion`(request: BriarAPI_ValidateManagedComputerPromotionRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ValidateManagedComputerPromotionResponse>

    @available(iOS 13, *)
    func `applyForManagedComputer`(request: BriarAPI_ApplyForManagedComputerRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ApplyForManagedComputerResponse>

    @available(iOS 13, *)
    func `retryManagedComputer`(request: BriarAPI_RetryManagedComputerRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_RetryManagedComputerResponse>

    @available(iOS 13, *)
    func `retireManagedComputer`(request: BriarAPI_RetireManagedComputerRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_RetireManagedComputerResponse>

    @available(iOS 13, *)
    func `terminateManagedComputer`(request: BriarAPI_TerminateManagedComputerRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_TerminateManagedComputerResponse>

    @available(iOS 13, *)
    func `createManagedComputerRemoteSession`(request: BriarAPI_CreateManagedComputerRemoteSessionRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateManagedComputerRemoteSessionResponse>

    @available(iOS 13, *)
    func `endManagedComputerRemoteSession`(request: BriarAPI_EndManagedComputerRemoteSessionRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_EndManagedComputerRemoteSessionResponse>

    @available(iOS 13, *)
    func `createManagedComputerSetupSession`(request: BriarAPI_CreateManagedComputerSetupSessionRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateManagedComputerSetupSessionResponse>

    @available(iOS 13, *)
    func `getManagedComputerSetupStatus`(request: BriarAPI_GetManagedComputerSetupStatusRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetManagedComputerSetupStatusResponse>
}

/// Concrete implementation of `BriarAPI_FleetServiceClientInterface`.
public final class BriarAPI_FleetServiceClient: BriarAPI_FleetServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `registerProjectExecutionWorker`(request: BriarAPI_RegisterProjectExecutionWorkerRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_RegisterProjectExecutionWorkerResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/RegisterProjectExecutionWorker", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `bindProjectExecutionWorker`(request: BriarAPI_BindProjectExecutionWorkerRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_BindProjectExecutionWorkerResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/BindProjectExecutionWorker", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `unbindProjectExecutionWorker`(request: BriarAPI_UnbindProjectExecutionWorkerRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UnbindProjectExecutionWorkerResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/UnbindProjectExecutionWorker", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listExecutionWorkers`(request: BriarAPI_ListExecutionWorkersRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListExecutionWorkersResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/ListExecutionWorkers", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `requestExecutionWorkerUpdate`(request: BriarAPI_RequestExecutionWorkerUpdateRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_RequestExecutionWorkerUpdateResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/RequestExecutionWorkerUpdate", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateExecutionWorker`(request: BriarAPI_UpdateExecutionWorkerRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateExecutionWorkerResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/UpdateExecutionWorker", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `deleteExecutionWorker`(request: BriarAPI_DeleteExecutionWorkerRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteExecutionWorkerResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/DeleteExecutionWorker", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getManagedComputerProduct`(request: BriarAPI_GetManagedComputerProductRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetManagedComputerProductResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/GetManagedComputerProduct", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listManagedComputers`(request: BriarAPI_ListManagedComputersRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListManagedComputersResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/ListManagedComputers", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getManagedComputer`(request: BriarAPI_GetManagedComputerRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetManagedComputerResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/GetManagedComputer", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `validateManagedComputerPromotion`(request: BriarAPI_ValidateManagedComputerPromotionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ValidateManagedComputerPromotionResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/ValidateManagedComputerPromotion", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `applyForManagedComputer`(request: BriarAPI_ApplyForManagedComputerRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ApplyForManagedComputerResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/ApplyForManagedComputer", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `retryManagedComputer`(request: BriarAPI_RetryManagedComputerRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_RetryManagedComputerResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/RetryManagedComputer", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `retireManagedComputer`(request: BriarAPI_RetireManagedComputerRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_RetireManagedComputerResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/RetireManagedComputer", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `terminateManagedComputer`(request: BriarAPI_TerminateManagedComputerRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_TerminateManagedComputerResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/TerminateManagedComputer", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createManagedComputerRemoteSession`(request: BriarAPI_CreateManagedComputerRemoteSessionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateManagedComputerRemoteSessionResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/CreateManagedComputerRemoteSession", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `endManagedComputerRemoteSession`(request: BriarAPI_EndManagedComputerRemoteSessionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_EndManagedComputerRemoteSessionResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/EndManagedComputerRemoteSession", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createManagedComputerSetupSession`(request: BriarAPI_CreateManagedComputerSetupSessionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateManagedComputerSetupSessionResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/CreateManagedComputerSetupSession", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getManagedComputerSetupStatus`(request: BriarAPI_GetManagedComputerSetupStatusRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetManagedComputerSetupStatusResponse> {
        return await self.client.unary(path: "/briar.app.v1.FleetService/GetManagedComputerSetupStatus", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let registerProjectExecutionWorker = Connect.MethodSpec(name: "RegisterProjectExecutionWorker", service: "briar.app.v1.FleetService", type: .unary)
            public static let bindProjectExecutionWorker = Connect.MethodSpec(name: "BindProjectExecutionWorker", service: "briar.app.v1.FleetService", type: .unary)
            public static let unbindProjectExecutionWorker = Connect.MethodSpec(name: "UnbindProjectExecutionWorker", service: "briar.app.v1.FleetService", type: .unary)
            public static let listExecutionWorkers = Connect.MethodSpec(name: "ListExecutionWorkers", service: "briar.app.v1.FleetService", type: .unary)
            public static let requestExecutionWorkerUpdate = Connect.MethodSpec(name: "RequestExecutionWorkerUpdate", service: "briar.app.v1.FleetService", type: .unary)
            public static let updateExecutionWorker = Connect.MethodSpec(name: "UpdateExecutionWorker", service: "briar.app.v1.FleetService", type: .unary)
            public static let deleteExecutionWorker = Connect.MethodSpec(name: "DeleteExecutionWorker", service: "briar.app.v1.FleetService", type: .unary)
            public static let getManagedComputerProduct = Connect.MethodSpec(name: "GetManagedComputerProduct", service: "briar.app.v1.FleetService", type: .unary)
            public static let listManagedComputers = Connect.MethodSpec(name: "ListManagedComputers", service: "briar.app.v1.FleetService", type: .unary)
            public static let getManagedComputer = Connect.MethodSpec(name: "GetManagedComputer", service: "briar.app.v1.FleetService", type: .unary)
            public static let validateManagedComputerPromotion = Connect.MethodSpec(name: "ValidateManagedComputerPromotion", service: "briar.app.v1.FleetService", type: .unary)
            public static let applyForManagedComputer = Connect.MethodSpec(name: "ApplyForManagedComputer", service: "briar.app.v1.FleetService", type: .unary)
            public static let retryManagedComputer = Connect.MethodSpec(name: "RetryManagedComputer", service: "briar.app.v1.FleetService", type: .unary)
            public static let retireManagedComputer = Connect.MethodSpec(name: "RetireManagedComputer", service: "briar.app.v1.FleetService", type: .unary)
            public static let terminateManagedComputer = Connect.MethodSpec(name: "TerminateManagedComputer", service: "briar.app.v1.FleetService", type: .unary)
            public static let createManagedComputerRemoteSession = Connect.MethodSpec(name: "CreateManagedComputerRemoteSession", service: "briar.app.v1.FleetService", type: .unary)
            public static let endManagedComputerRemoteSession = Connect.MethodSpec(name: "EndManagedComputerRemoteSession", service: "briar.app.v1.FleetService", type: .unary)
            public static let createManagedComputerSetupSession = Connect.MethodSpec(name: "CreateManagedComputerSetupSession", service: "briar.app.v1.FleetService", type: .unary)
            public static let getManagedComputerSetupStatus = Connect.MethodSpec(name: "GetManagedComputerSetupStatus", service: "briar.app.v1.FleetService", type: .unary)
        }
    }
}
