// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/github.proto
//

import Connect
import Foundation
import SwiftProtobuf

/// GitHubIntegrationService owns organization installation discovery and the
/// start of the browser installation flow. OAuth/install callbacks and signed
/// webhooks intentionally remain ordinary HTTP endpoints.
public protocol BriarAPI_GitHubIntegrationServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `getGitHubIntegration`(request: BriarAPI_GetGitHubIntegrationRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetGitHubIntegrationResponse>

    @available(iOS 13, *)
    func `beginGitHubInstallation`(request: BriarAPI_BeginGitHubInstallationRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_BeginGitHubInstallationResponse>
}

/// Concrete implementation of `BriarAPI_GitHubIntegrationServiceClientInterface`.
public final class BriarAPI_GitHubIntegrationServiceClient: BriarAPI_GitHubIntegrationServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `getGitHubIntegration`(request: BriarAPI_GetGitHubIntegrationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetGitHubIntegrationResponse> {
        return await self.client.unary(path: "/briar.app.v1.GitHubIntegrationService/GetGitHubIntegration", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `beginGitHubInstallation`(request: BriarAPI_BeginGitHubInstallationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_BeginGitHubInstallationResponse> {
        return await self.client.unary(path: "/briar.app.v1.GitHubIntegrationService/BeginGitHubInstallation", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let getGitHubIntegration = Connect.MethodSpec(name: "GetGitHubIntegration", service: "briar.app.v1.GitHubIntegrationService", type: .unary)
            public static let beginGitHubInstallation = Connect.MethodSpec(name: "BeginGitHubInstallation", service: "briar.app.v1.GitHubIntegrationService", type: .unary)
        }
    }
}

/// ProjectGitHubService owns typed project-scoped GitHub App operations used by
/// the app and CLI. The arbitrary GraphQL escape hatch intentionally remains an
/// ordinary HTTP endpoint because google.protobuf.Struct would add no contract.
public protocol BriarAPI_ProjectGitHubServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `createProjectGitHubCredential`(request: BriarAPI_CreateProjectGitHubCredentialRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateProjectGitHubCredentialResponse>

    @available(iOS 13, *)
    func `getProjectGitHubRepository`(request: BriarAPI_GetProjectGitHubRepositoryRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetProjectGitHubRepositoryResponse>

    @available(iOS 13, *)
    func `createGitHubPullRequest`(request: BriarAPI_CreateGitHubPullRequestRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateGitHubPullRequestResponse>

    @available(iOS 13, *)
    func `getGitHubPullRequest`(request: BriarAPI_GetGitHubPullRequestRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetGitHubPullRequestResponse>

    @available(iOS 13, *)
    func `updateGitHubPullRequest`(request: BriarAPI_UpdateGitHubPullRequestRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateGitHubPullRequestResponse>

    @available(iOS 13, *)
    func `mergeGitHubPullRequest`(request: BriarAPI_MergeGitHubPullRequestRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_MergeGitHubPullRequestResponse>

    @available(iOS 13, *)
    func `createGitHubCommitStatus`(request: BriarAPI_CreateGitHubCommitStatusRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateGitHubCommitStatusResponse>
}

/// Concrete implementation of `BriarAPI_ProjectGitHubServiceClientInterface`.
public final class BriarAPI_ProjectGitHubServiceClient: BriarAPI_ProjectGitHubServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `createProjectGitHubCredential`(request: BriarAPI_CreateProjectGitHubCredentialRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateProjectGitHubCredentialResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectGitHubService/CreateProjectGitHubCredential", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getProjectGitHubRepository`(request: BriarAPI_GetProjectGitHubRepositoryRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetProjectGitHubRepositoryResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectGitHubService/GetProjectGitHubRepository", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createGitHubPullRequest`(request: BriarAPI_CreateGitHubPullRequestRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateGitHubPullRequestResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectGitHubService/CreateGitHubPullRequest", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getGitHubPullRequest`(request: BriarAPI_GetGitHubPullRequestRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetGitHubPullRequestResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectGitHubService/GetGitHubPullRequest", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateGitHubPullRequest`(request: BriarAPI_UpdateGitHubPullRequestRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateGitHubPullRequestResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectGitHubService/UpdateGitHubPullRequest", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `mergeGitHubPullRequest`(request: BriarAPI_MergeGitHubPullRequestRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_MergeGitHubPullRequestResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectGitHubService/MergeGitHubPullRequest", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createGitHubCommitStatus`(request: BriarAPI_CreateGitHubCommitStatusRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateGitHubCommitStatusResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectGitHubService/CreateGitHubCommitStatus", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let createProjectGitHubCredential = Connect.MethodSpec(name: "CreateProjectGitHubCredential", service: "briar.app.v1.ProjectGitHubService", type: .unary)
            public static let getProjectGitHubRepository = Connect.MethodSpec(name: "GetProjectGitHubRepository", service: "briar.app.v1.ProjectGitHubService", type: .unary)
            public static let createGitHubPullRequest = Connect.MethodSpec(name: "CreateGitHubPullRequest", service: "briar.app.v1.ProjectGitHubService", type: .unary)
            public static let getGitHubPullRequest = Connect.MethodSpec(name: "GetGitHubPullRequest", service: "briar.app.v1.ProjectGitHubService", type: .unary)
            public static let updateGitHubPullRequest = Connect.MethodSpec(name: "UpdateGitHubPullRequest", service: "briar.app.v1.ProjectGitHubService", type: .unary)
            public static let mergeGitHubPullRequest = Connect.MethodSpec(name: "MergeGitHubPullRequest", service: "briar.app.v1.ProjectGitHubService", type: .unary)
            public static let createGitHubCommitStatus = Connect.MethodSpec(name: "CreateGitHubCommitStatus", service: "briar.app.v1.ProjectGitHubService", type: .unary)
        }
    }
}
