// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: briar/app/v1/inbox.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct BriarAPI_GetInboxFeedRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var organizationID: String = String()

  public var knownVersion: String {
    get {_knownVersion ?? String()}
    set {_knownVersion = newValue}
  }
  /// Returns true if `knownVersion` has been explicitly set.
  public var hasKnownVersion: Bool {self._knownVersion != nil}
  /// Clears the value of `knownVersion`. Subsequent reads from it will return its default value.
  public mutating func clearKnownVersion() {self._knownVersion = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _knownVersion: String? = nil
}

public nonisolated struct BriarAPI_GetInboxFeedResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var messages: [BriarAPI_InboxFeedMessage] = []

  public var subscribedIssueIds: [String] = []

  public var generatedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_generatedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_generatedAt = newValue}
  }
  /// Returns true if `generatedAt` has been explicitly set.
  public var hasGeneratedAt: Bool {self._generatedAt != nil}
  /// Clears the value of `generatedAt`. Subsequent reads from it will return its default value.
  public mutating func clearGeneratedAt() {self._generatedAt = nil}

  public var version: String = String()

  public var unchanged: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _generatedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public nonisolated struct BriarAPI_GetInboxReadStatesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_GetInboxReadStatesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var readVersions: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_PutInboxReadStatesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var readVersions: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_PutInboxReadStatesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var readVersions: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_DeleteInboxReadStateRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var messageID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_DeleteInboxReadStateResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var readVersions: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_InboxMessageIdentity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var projectID: String = String()

  public var projectName: String = String()

  public var targetID: String = String()

  public var title: String = String()

  public var occurredAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_occurredAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_occurredAt = newValue}
  }
  /// Returns true if `occurredAt` has been explicitly set.
  public var hasOccurredAt: Bool {self._occurredAt != nil}
  /// Clears the value of `occurredAt`. Subsequent reads from it will return its default value.
  public mutating func clearOccurredAt() {self._occurredAt = nil}

  public var version: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _occurredAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public nonisolated struct BriarAPI_InboxIssueMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var runNumber: UInt32 = 0

  public var status: BriarAPI_RunStatus = .unspecified

  public var workflowStage: String {
    get {_workflowStage ?? String()}
    set {_workflowStage = newValue}
  }
  /// Returns true if `workflowStage` has been explicitly set.
  public var hasWorkflowStage: Bool {self._workflowStage != nil}
  /// Clears the value of `workflowStage`. Subsequent reads from it will return its default value.
  public mutating func clearWorkflowStage() {self._workflowStage = nil}

  public var workflowStageLabel: String {
    get {_workflowStageLabel ?? String()}
    set {_workflowStageLabel = newValue}
  }
  /// Returns true if `workflowStageLabel` has been explicitly set.
  public var hasWorkflowStageLabel: Bool {self._workflowStageLabel != nil}
  /// Clears the value of `workflowStageLabel`. Subsequent reads from it will return its default value.
  public mutating func clearWorkflowStageLabel() {self._workflowStageLabel = nil}

  public var priority: UInt32 {
    get {_priority ?? 0}
    set {_priority = newValue}
  }
  /// Returns true if `priority` has been explicitly set.
  public var hasPriority: Bool {self._priority != nil}
  /// Clears the value of `priority`. Subsequent reads from it will return its default value.
  public mutating func clearPriority() {self._priority = nil}

  public var structuredResult: BriarAPI_StructuredRunResult {
    get {_structuredResult ?? BriarAPI_StructuredRunResult()}
    set {_structuredResult = newValue}
  }
  /// Returns true if `structuredResult` has been explicitly set.
  public var hasStructuredResult: Bool {self._structuredResult != nil}
  /// Clears the value of `structuredResult`. Subsequent reads from it will return its default value.
  public mutating func clearStructuredResult() {self._structuredResult = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _workflowStage: String? = nil
  fileprivate var _workflowStageLabel: String? = nil
  fileprivate var _priority: UInt32? = nil
  fileprivate var _structuredResult: BriarAPI_StructuredRunResult? = nil
}

public nonisolated struct BriarAPI_InboxConversationMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var messageID: String = String()

  public var rootMessageID: String = String()

  public var body: String = String()

  public var blocks: [BriarAPI_MessageBlock] = []

  public var authorName: String = String()

  public var authorImage: String {
    get {_authorImage ?? String()}
    set {_authorImage = newValue}
  }
  /// Returns true if `authorImage` has been explicitly set.
  public var hasAuthorImage: Bool {self._authorImage != nil}
  /// Clears the value of `authorImage`. Subsequent reads from it will return its default value.
  public mutating func clearAuthorImage() {self._authorImage = nil}

  public var issueKey: String {
    get {_issueKey ?? String()}
    set {_issueKey = newValue}
  }
  /// Returns true if `issueKey` has been explicitly set.
  public var hasIssueKey: Bool {self._issueKey != nil}
  /// Clears the value of `issueKey`. Subsequent reads from it will return its default value.
  public mutating func clearIssueKey() {self._issueKey = nil}

  public var reason: BriarAPI_NotificationReason = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _authorImage: String? = nil
  fileprivate var _issueKey: String? = nil
}

public nonisolated struct BriarAPI_InboxChannelMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var channelID: String = String()

  public var channelName: String = String()

  public var messageID: String = String()

  public var rootMessageID: String = String()

  public var body: String = String()

  public var authorName: String = String()

  public var authorImage: String {
    get {_authorImage ?? String()}
    set {_authorImage = newValue}
  }
  /// Returns true if `authorImage` has been explicitly set.
  public var hasAuthorImage: Bool {self._authorImage != nil}
  /// Clears the value of `authorImage`. Subsequent reads from it will return its default value.
  public mutating func clearAuthorImage() {self._authorImage = nil}

  public var reason: BriarAPI_NotificationReason = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _authorImage: String? = nil
}

public nonisolated struct BriarAPI_InboxSessionMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var status: BriarAPI_InboxSessionMessage.Status = .unspecified

  public var agentName: String {
    get {_agentName ?? String()}
    set {_agentName = newValue}
  }
  /// Returns true if `agentName` has been explicitly set.
  public var hasAgentName: Bool {self._agentName != nil}
  /// Clears the value of `agentName`. Subsequent reads from it will return its default value.
  public mutating func clearAgentName() {self._agentName = nil}

  public var issueCount: UInt32 = 0

  public var error: String {
    get {_error ?? String()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var summary: String {
    get {_summary ?? String()}
    set {_summary = newValue}
  }
  /// Returns true if `summary` has been explicitly set.
  public var hasSummary: Bool {self._summary != nil}
  /// Clears the value of `summary`. Subsequent reads from it will return its default value.
  public mutating func clearSummary() {self._summary = nil}

  public var requiresAttention: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum Status: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unspecified // = 0
    case completed // = 1
    case failed // = 2
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .completed
      case 2: self = .failed
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .completed: return 1
      case .failed: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [BriarAPI_InboxSessionMessage.Status] = [
      .unspecified,
      .completed,
      .failed,
    ]

  }

  public init() {}

  fileprivate var _agentName: String? = nil
  fileprivate var _error: String? = nil
  fileprivate var _summary: String? = nil
}

public nonisolated struct BriarAPI_InboxFeedMessage: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var identity: BriarAPI_InboxMessageIdentity {
    get {_storage._identity ?? BriarAPI_InboxMessageIdentity()}
    set {_uniqueStorage()._identity = newValue}
  }
  /// Returns true if `identity` has been explicitly set.
  public var hasIdentity: Bool {_storage._identity != nil}
  /// Clears the value of `identity`. Subsequent reads from it will return its default value.
  public mutating func clearIdentity() {_uniqueStorage()._identity = nil}

  public var content: OneOf_Content? {
    get {return _storage._content}
    set {_uniqueStorage()._content = newValue}
  }

  public var issue: BriarAPI_InboxIssueMessage {
    get {
      if case .issue(let v)? = _storage._content {return v}
      return BriarAPI_InboxIssueMessage()
    }
    set {_uniqueStorage()._content = .issue(newValue)}
  }

  public var conversation: BriarAPI_InboxConversationMessage {
    get {
      if case .conversation(let v)? = _storage._content {return v}
      return BriarAPI_InboxConversationMessage()
    }
    set {_uniqueStorage()._content = .conversation(newValue)}
  }

  public var channel: BriarAPI_InboxChannelMessage {
    get {
      if case .channel(let v)? = _storage._content {return v}
      return BriarAPI_InboxChannelMessage()
    }
    set {_uniqueStorage()._content = .channel(newValue)}
  }

  public var session: BriarAPI_InboxSessionMessage {
    get {
      if case .session(let v)? = _storage._content {return v}
      return BriarAPI_InboxSessionMessage()
    }
    set {_uniqueStorage()._content = .session(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Content: Equatable, Sendable {
    case issue(BriarAPI_InboxIssueMessage)
    case conversation(BriarAPI_InboxConversationMessage)
    case channel(BriarAPI_InboxChannelMessage)
    case session(BriarAPI_InboxSessionMessage)

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "briar.app.v1"

nonisolated extension BriarAPI_GetInboxFeedRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetInboxFeedRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}organization_id\0\u{3}known_version\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.organizationID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._knownVersion) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.organizationID.isEmpty {
      try visitor.visitSingularStringField(value: self.organizationID, fieldNumber: 1)
    }
    try { if let v = self._knownVersion {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_GetInboxFeedRequest, rhs: BriarAPI_GetInboxFeedRequest) -> Bool {
    if lhs.organizationID != rhs.organizationID {return false}
    if lhs._knownVersion != rhs._knownVersion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_GetInboxFeedResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetInboxFeedResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}messages\0\u{3}subscribed_issue_ids\0\u{3}generated_at\0\u{1}version\0\u{1}unchanged\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.messages) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.subscribedIssueIds) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._generatedAt) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.unchanged) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.messages.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.messages, fieldNumber: 1)
    }
    if !self.subscribedIssueIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.subscribedIssueIds, fieldNumber: 2)
    }
    try { if let v = self._generatedAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 4)
    }
    if self.unchanged != false {
      try visitor.visitSingularBoolField(value: self.unchanged, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_GetInboxFeedResponse, rhs: BriarAPI_GetInboxFeedResponse) -> Bool {
    if lhs.messages != rhs.messages {return false}
    if lhs.subscribedIssueIds != rhs.subscribedIssueIds {return false}
    if lhs._generatedAt != rhs._generatedAt {return false}
    if lhs.version != rhs.version {return false}
    if lhs.unchanged != rhs.unchanged {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_GetInboxReadStatesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetInboxReadStatesRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_GetInboxReadStatesRequest, rhs: BriarAPI_GetInboxReadStatesRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_GetInboxReadStatesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetInboxReadStatesResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}read_versions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.readVersions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.readVersions.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.readVersions, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_GetInboxReadStatesResponse, rhs: BriarAPI_GetInboxReadStatesResponse) -> Bool {
    if lhs.readVersions != rhs.readVersions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_PutInboxReadStatesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PutInboxReadStatesRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}read_versions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.readVersions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.readVersions.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.readVersions, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_PutInboxReadStatesRequest, rhs: BriarAPI_PutInboxReadStatesRequest) -> Bool {
    if lhs.readVersions != rhs.readVersions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_PutInboxReadStatesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PutInboxReadStatesResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}read_versions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.readVersions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.readVersions.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.readVersions, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_PutInboxReadStatesResponse, rhs: BriarAPI_PutInboxReadStatesResponse) -> Bool {
    if lhs.readVersions != rhs.readVersions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_DeleteInboxReadStateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeleteInboxReadStateRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}message_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.messageID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.messageID.isEmpty {
      try visitor.visitSingularStringField(value: self.messageID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_DeleteInboxReadStateRequest, rhs: BriarAPI_DeleteInboxReadStateRequest) -> Bool {
    if lhs.messageID != rhs.messageID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_DeleteInboxReadStateResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeleteInboxReadStateResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}read_versions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.readVersions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.readVersions.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.readVersions, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_DeleteInboxReadStateResponse, rhs: BriarAPI_DeleteInboxReadStateResponse) -> Bool {
    if lhs.readVersions != rhs.readVersions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_InboxMessageIdentity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InboxMessageIdentity"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}project_id\0\u{3}project_name\0\u{3}target_id\0\u{1}title\0\u{3}occurred_at\0\u{1}version\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.projectID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.projectName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.targetID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._occurredAt) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.version) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.projectID.isEmpty {
      try visitor.visitSingularStringField(value: self.projectID, fieldNumber: 2)
    }
    if !self.projectName.isEmpty {
      try visitor.visitSingularStringField(value: self.projectName, fieldNumber: 3)
    }
    if !self.targetID.isEmpty {
      try visitor.visitSingularStringField(value: self.targetID, fieldNumber: 4)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 5)
    }
    try { if let v = self._occurredAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_InboxMessageIdentity, rhs: BriarAPI_InboxMessageIdentity) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.projectID != rhs.projectID {return false}
    if lhs.projectName != rhs.projectName {return false}
    if lhs.targetID != rhs.targetID {return false}
    if lhs.title != rhs.title {return false}
    if lhs._occurredAt != rhs._occurredAt {return false}
    if lhs.version != rhs.version {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_InboxIssueMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InboxIssueMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}run_number\0\u{1}status\0\u{3}workflow_stage\0\u{3}workflow_stage_label\0\u{1}priority\0\u{3}structured_result\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.runNumber) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._workflowStage) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._workflowStageLabel) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self._priority) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._structuredResult) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.runNumber != 0 {
      try visitor.visitSingularUInt32Field(value: self.runNumber, fieldNumber: 1)
    }
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 2)
    }
    try { if let v = self._workflowStage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._workflowStageLabel {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._priority {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._structuredResult {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_InboxIssueMessage, rhs: BriarAPI_InboxIssueMessage) -> Bool {
    if lhs.runNumber != rhs.runNumber {return false}
    if lhs.status != rhs.status {return false}
    if lhs._workflowStage != rhs._workflowStage {return false}
    if lhs._workflowStageLabel != rhs._workflowStageLabel {return false}
    if lhs._priority != rhs._priority {return false}
    if lhs._structuredResult != rhs._structuredResult {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_InboxConversationMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InboxConversationMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}message_id\0\u{3}root_message_id\0\u{1}body\0\u{1}blocks\0\u{3}author_name\0\u{3}author_image\0\u{3}issue_key\0\u{1}reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.messageID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.rootMessageID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.body) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.blocks) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.authorName) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._authorImage) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._issueKey) }()
      case 8: try { try decoder.decodeSingularEnumField(value: &self.reason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.messageID.isEmpty {
      try visitor.visitSingularStringField(value: self.messageID, fieldNumber: 1)
    }
    if !self.rootMessageID.isEmpty {
      try visitor.visitSingularStringField(value: self.rootMessageID, fieldNumber: 2)
    }
    if !self.body.isEmpty {
      try visitor.visitSingularStringField(value: self.body, fieldNumber: 3)
    }
    if !self.blocks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.blocks, fieldNumber: 4)
    }
    if !self.authorName.isEmpty {
      try visitor.visitSingularStringField(value: self.authorName, fieldNumber: 5)
    }
    try { if let v = self._authorImage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._issueKey {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    if self.reason != .unspecified {
      try visitor.visitSingularEnumField(value: self.reason, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_InboxConversationMessage, rhs: BriarAPI_InboxConversationMessage) -> Bool {
    if lhs.messageID != rhs.messageID {return false}
    if lhs.rootMessageID != rhs.rootMessageID {return false}
    if lhs.body != rhs.body {return false}
    if lhs.blocks != rhs.blocks {return false}
    if lhs.authorName != rhs.authorName {return false}
    if lhs._authorImage != rhs._authorImage {return false}
    if lhs._issueKey != rhs._issueKey {return false}
    if lhs.reason != rhs.reason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_InboxChannelMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InboxChannelMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}channel_id\0\u{3}channel_name\0\u{3}message_id\0\u{3}root_message_id\0\u{1}body\0\u{3}author_name\0\u{3}author_image\0\u{1}reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.channelID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.channelName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.messageID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.rootMessageID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.body) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.authorName) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._authorImage) }()
      case 8: try { try decoder.decodeSingularEnumField(value: &self.reason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.channelID.isEmpty {
      try visitor.visitSingularStringField(value: self.channelID, fieldNumber: 1)
    }
    if !self.channelName.isEmpty {
      try visitor.visitSingularStringField(value: self.channelName, fieldNumber: 2)
    }
    if !self.messageID.isEmpty {
      try visitor.visitSingularStringField(value: self.messageID, fieldNumber: 3)
    }
    if !self.rootMessageID.isEmpty {
      try visitor.visitSingularStringField(value: self.rootMessageID, fieldNumber: 4)
    }
    if !self.body.isEmpty {
      try visitor.visitSingularStringField(value: self.body, fieldNumber: 5)
    }
    if !self.authorName.isEmpty {
      try visitor.visitSingularStringField(value: self.authorName, fieldNumber: 6)
    }
    try { if let v = self._authorImage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    if self.reason != .unspecified {
      try visitor.visitSingularEnumField(value: self.reason, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_InboxChannelMessage, rhs: BriarAPI_InboxChannelMessage) -> Bool {
    if lhs.channelID != rhs.channelID {return false}
    if lhs.channelName != rhs.channelName {return false}
    if lhs.messageID != rhs.messageID {return false}
    if lhs.rootMessageID != rhs.rootMessageID {return false}
    if lhs.body != rhs.body {return false}
    if lhs.authorName != rhs.authorName {return false}
    if lhs._authorImage != rhs._authorImage {return false}
    if lhs.reason != rhs.reason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_InboxSessionMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InboxSessionMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0\u{3}agent_name\0\u{3}issue_count\0\u{1}error\0\u{1}summary\0\u{3}requires_attention\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._agentName) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.issueCount) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._error) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._summary) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.requiresAttention) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    try { if let v = self._agentName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    if self.issueCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.issueCount, fieldNumber: 3)
    }
    try { if let v = self._error {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._summary {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    if self.requiresAttention != false {
      try visitor.visitSingularBoolField(value: self.requiresAttention, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_InboxSessionMessage, rhs: BriarAPI_InboxSessionMessage) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs._agentName != rhs._agentName {return false}
    if lhs.issueCount != rhs.issueCount {return false}
    if lhs._error != rhs._error {return false}
    if lhs._summary != rhs._summary {return false}
    if lhs.requiresAttention != rhs.requiresAttention {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_InboxSessionMessage.Status: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STATUS_UNSPECIFIED\0\u{1}STATUS_COMPLETED\0\u{1}STATUS_FAILED\0")
}

nonisolated extension BriarAPI_InboxFeedMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InboxFeedMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}identity\0\u{1}issue\0\u{1}conversation\0\u{1}channel\0\u{1}session\0")

  fileprivate class _StorageClass {
    var _identity: BriarAPI_InboxMessageIdentity? = nil
    var _content: BriarAPI_InboxFeedMessage.OneOf_Content?

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _identity = source._identity
      _content = source._content
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._identity) }()
        case 2: try {
          var v: BriarAPI_InboxIssueMessage?
          var hadOneofValue = false
          if let current = _storage._content {
            hadOneofValue = true
            if case .issue(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._content = .issue(v)
          }
        }()
        case 3: try {
          var v: BriarAPI_InboxConversationMessage?
          var hadOneofValue = false
          if let current = _storage._content {
            hadOneofValue = true
            if case .conversation(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._content = .conversation(v)
          }
        }()
        case 4: try {
          var v: BriarAPI_InboxChannelMessage?
          var hadOneofValue = false
          if let current = _storage._content {
            hadOneofValue = true
            if case .channel(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._content = .channel(v)
          }
        }()
        case 5: try {
          var v: BriarAPI_InboxSessionMessage?
          var hadOneofValue = false
          if let current = _storage._content {
            hadOneofValue = true
            if case .session(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._content = .session(v)
          }
        }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._identity {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      switch _storage._content {
      case .issue?: try {
        guard case .issue(let v)? = _storage._content else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }()
      case .conversation?: try {
        guard case .conversation(let v)? = _storage._content else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }()
      case .channel?: try {
        guard case .channel(let v)? = _storage._content else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }()
      case .session?: try {
        guard case .session(let v)? = _storage._content else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }()
      case nil: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_InboxFeedMessage, rhs: BriarAPI_InboxFeedMessage) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._identity != rhs_storage._identity {return false}
        if _storage._content != rhs_storage._content {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
