// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: briar/app/v1/linear_import.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct BriarAPI_LinearImportViewer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var email: String {
    get {_email ?? String()}
    set {_email = newValue}
  }
  /// Returns true if `email` has been explicitly set.
  public var hasEmail: Bool {self._email != nil}
  /// Clears the value of `email`. Subsequent reads from it will return its default value.
  public mutating func clearEmail() {self._email = nil}

  public var organizationName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _email: String? = nil
}

public nonisolated struct BriarAPI_LinearTeam: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var name: String = String()

  public var key: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_LinearWorkflowState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var name: String = String()

  public var type: String = String()

  public var color: String = String()

  public var position: Double = 0

  public var teamID: String = String()

  public var teamKey: String = String()

  public var teamName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_ConnectLinearImportRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var projectID: String = String()

  public var apiKey: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_ConnectLinearImportResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var viewer: BriarAPI_LinearImportViewer {
    get {_viewer ?? BriarAPI_LinearImportViewer()}
    set {_viewer = newValue}
  }
  /// Returns true if `viewer` has been explicitly set.
  public var hasViewer: Bool {self._viewer != nil}
  /// Clears the value of `viewer`. Subsequent reads from it will return its default value.
  public mutating func clearViewer() {self._viewer = nil}

  public var teams: [BriarAPI_LinearTeam] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _viewer: BriarAPI_LinearImportViewer? = nil
}

public nonisolated struct BriarAPI_ListLinearImportStatesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var projectID: String = String()

  public var apiKey: String = String()

  public var teamIds: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_ListLinearImportStatesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var states: [BriarAPI_LinearWorkflowState] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_LinearStatusMapping: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var stateID: String = String()

  /// A workflow-stage placement always means RUNNING. All other placements use
  /// an explicit persisted run status, eliminating the former string mini-language.
  public var placement: BriarAPI_LinearStatusMapping.OneOf_Placement? = nil

  public var status: BriarAPI_RunStatus {
    get {
      if case .status(let v)? = placement {return v}
      return .unspecified
    }
    set {placement = .status(newValue)}
  }

  public var workflowStageID: String {
    get {
      if case .workflowStageID(let v)? = placement {return v}
      return String()
    }
    set {placement = .workflowStageID(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// A workflow-stage placement always means RUNNING. All other placements use
  /// an explicit persisted run status, eliminating the former string mini-language.
  public nonisolated enum OneOf_Placement: Equatable, Sendable {
    case status(BriarAPI_RunStatus)
    case workflowStageID(String)

  }

  public init() {}
}

public nonisolated struct BriarAPI_ImportLinearIssuesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var projectID: String = String()

  public var apiKey: String = String()

  public var teamIds: [String] = []

  public var statusMappings: [BriarAPI_LinearStatusMapping] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_ImportLinearIssuesResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var imported: UInt32 {
    get {_storage._imported}
    set {_uniqueStorage()._imported = newValue}
  }

  public var skipped: UInt32 {
    get {_storage._skipped}
    set {_uniqueStorage()._skipped = newValue}
  }

  public var failed: UInt32 {
    get {_storage._failed}
    set {_uniqueStorage()._failed = newValue}
  }

  public var total: UInt32 {
    get {_storage._total}
    set {_uniqueStorage()._total = newValue}
  }

  public var truncated: Bool {
    get {_storage._truncated}
    set {_uniqueStorage()._truncated = newValue}
  }

  public var relations: BriarAPI_LinearImportRelations {
    get {_storage._relations ?? BriarAPI_LinearImportRelations()}
    set {_uniqueStorage()._relations = newValue}
  }
  /// Returns true if `relations` has been explicitly set.
  public var hasRelations: Bool {_storage._relations != nil}
  /// Clears the value of `relations`. Subsequent reads from it will return its default value.
  public mutating func clearRelations() {_uniqueStorage()._relations = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct BriarAPI_LinearImportRelationCounter: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var linked: UInt32 = 0

  public var skipped: UInt32 = 0

  public var outsideScope: UInt32 = 0

  public var cycles: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_LinearImportUnsupportedRelations: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var duplicate: UInt32 = 0

  public var similar: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct BriarAPI_LinearImportRelations: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var hierarchy: BriarAPI_LinearImportRelationCounter {
    get {_hierarchy ?? BriarAPI_LinearImportRelationCounter()}
    set {_hierarchy = newValue}
  }
  /// Returns true if `hierarchy` has been explicitly set.
  public var hasHierarchy: Bool {self._hierarchy != nil}
  /// Clears the value of `hierarchy`. Subsequent reads from it will return its default value.
  public mutating func clearHierarchy() {self._hierarchy = nil}

  public var related: BriarAPI_LinearImportRelationCounter {
    get {_related ?? BriarAPI_LinearImportRelationCounter()}
    set {_related = newValue}
  }
  /// Returns true if `related` has been explicitly set.
  public var hasRelated: Bool {self._related != nil}
  /// Clears the value of `related`. Subsequent reads from it will return its default value.
  public mutating func clearRelated() {self._related = nil}

  public var dependencies: BriarAPI_LinearImportRelationCounter {
    get {_dependencies ?? BriarAPI_LinearImportRelationCounter()}
    set {_dependencies = newValue}
  }
  /// Returns true if `dependencies` has been explicitly set.
  public var hasDependencies: Bool {self._dependencies != nil}
  /// Clears the value of `dependencies`. Subsequent reads from it will return its default value.
  public mutating func clearDependencies() {self._dependencies = nil}

  public var unsupported: BriarAPI_LinearImportUnsupportedRelations {
    get {_unsupported ?? BriarAPI_LinearImportUnsupportedRelations()}
    set {_unsupported = newValue}
  }
  /// Returns true if `unsupported` has been explicitly set.
  public var hasUnsupported: Bool {self._unsupported != nil}
  /// Clears the value of `unsupported`. Subsequent reads from it will return its default value.
  public mutating func clearUnsupported() {self._unsupported = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _hierarchy: BriarAPI_LinearImportRelationCounter? = nil
  fileprivate var _related: BriarAPI_LinearImportRelationCounter? = nil
  fileprivate var _dependencies: BriarAPI_LinearImportRelationCounter? = nil
  fileprivate var _unsupported: BriarAPI_LinearImportUnsupportedRelations? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "briar.app.v1"

nonisolated extension BriarAPI_LinearImportViewer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LinearImportViewer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}email\0\u{3}organization_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._email) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.organizationName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try { if let v = self._email {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    if !self.organizationName.isEmpty {
      try visitor.visitSingularStringField(value: self.organizationName, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_LinearImportViewer, rhs: BriarAPI_LinearImportViewer) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs._email != rhs._email {return false}
    if lhs.organizationName != rhs.organizationName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_LinearTeam: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LinearTeam"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.key) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_LinearTeam, rhs: BriarAPI_LinearTeam) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.key != rhs.key {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_LinearWorkflowState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LinearWorkflowState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}type\0\u{1}color\0\u{1}position\0\u{3}team_id\0\u{3}team_key\0\u{3}team_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.color) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.position) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.teamID) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.teamKey) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.teamName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 3)
    }
    if !self.color.isEmpty {
      try visitor.visitSingularStringField(value: self.color, fieldNumber: 4)
    }
    if self.position.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.position, fieldNumber: 5)
    }
    if !self.teamID.isEmpty {
      try visitor.visitSingularStringField(value: self.teamID, fieldNumber: 6)
    }
    if !self.teamKey.isEmpty {
      try visitor.visitSingularStringField(value: self.teamKey, fieldNumber: 7)
    }
    if !self.teamName.isEmpty {
      try visitor.visitSingularStringField(value: self.teamName, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_LinearWorkflowState, rhs: BriarAPI_LinearWorkflowState) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.type != rhs.type {return false}
    if lhs.color != rhs.color {return false}
    if lhs.position != rhs.position {return false}
    if lhs.teamID != rhs.teamID {return false}
    if lhs.teamKey != rhs.teamKey {return false}
    if lhs.teamName != rhs.teamName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_ConnectLinearImportRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConnectLinearImportRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}project_id\0\u{3}api_key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.projectID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.apiKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.projectID.isEmpty {
      try visitor.visitSingularStringField(value: self.projectID, fieldNumber: 1)
    }
    if !self.apiKey.isEmpty {
      try visitor.visitSingularStringField(value: self.apiKey, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_ConnectLinearImportRequest, rhs: BriarAPI_ConnectLinearImportRequest) -> Bool {
    if lhs.projectID != rhs.projectID {return false}
    if lhs.apiKey != rhs.apiKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_ConnectLinearImportResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConnectLinearImportResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}viewer\0\u{1}teams\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._viewer) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.teams) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._viewer {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.teams.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.teams, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_ConnectLinearImportResponse, rhs: BriarAPI_ConnectLinearImportResponse) -> Bool {
    if lhs._viewer != rhs._viewer {return false}
    if lhs.teams != rhs.teams {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_ListLinearImportStatesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListLinearImportStatesRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}project_id\0\u{3}api_key\0\u{3}team_ids\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.projectID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.apiKey) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.teamIds) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.projectID.isEmpty {
      try visitor.visitSingularStringField(value: self.projectID, fieldNumber: 1)
    }
    if !self.apiKey.isEmpty {
      try visitor.visitSingularStringField(value: self.apiKey, fieldNumber: 2)
    }
    if !self.teamIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.teamIds, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_ListLinearImportStatesRequest, rhs: BriarAPI_ListLinearImportStatesRequest) -> Bool {
    if lhs.projectID != rhs.projectID {return false}
    if lhs.apiKey != rhs.apiKey {return false}
    if lhs.teamIds != rhs.teamIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_ListLinearImportStatesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListLinearImportStatesResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}states\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.states) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.states.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.states, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_ListLinearImportStatesResponse, rhs: BriarAPI_ListLinearImportStatesResponse) -> Bool {
    if lhs.states != rhs.states {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_LinearStatusMapping: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LinearStatusMapping"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}state_id\0\u{1}status\0\u{3}workflow_stage_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.stateID) }()
      case 2: try {
        var v: BriarAPI_RunStatus?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.placement != nil {try decoder.handleConflictingOneOf()}
          self.placement = .status(v)
        }
      }()
      case 3: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.placement != nil {try decoder.handleConflictingOneOf()}
          self.placement = .workflowStageID(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.stateID.isEmpty {
      try visitor.visitSingularStringField(value: self.stateID, fieldNumber: 1)
    }
    switch self.placement {
    case .status?: try {
      guard case .status(let v)? = self.placement else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    }()
    case .workflowStageID?: try {
      guard case .workflowStageID(let v)? = self.placement else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_LinearStatusMapping, rhs: BriarAPI_LinearStatusMapping) -> Bool {
    if lhs.stateID != rhs.stateID {return false}
    if lhs.placement != rhs.placement {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_ImportLinearIssuesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ImportLinearIssuesRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}project_id\0\u{3}api_key\0\u{3}team_ids\0\u{3}status_mappings\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.projectID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.apiKey) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.teamIds) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.statusMappings) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.projectID.isEmpty {
      try visitor.visitSingularStringField(value: self.projectID, fieldNumber: 1)
    }
    if !self.apiKey.isEmpty {
      try visitor.visitSingularStringField(value: self.apiKey, fieldNumber: 2)
    }
    if !self.teamIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.teamIds, fieldNumber: 3)
    }
    if !self.statusMappings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.statusMappings, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_ImportLinearIssuesRequest, rhs: BriarAPI_ImportLinearIssuesRequest) -> Bool {
    if lhs.projectID != rhs.projectID {return false}
    if lhs.apiKey != rhs.apiKey {return false}
    if lhs.teamIds != rhs.teamIds {return false}
    if lhs.statusMappings != rhs.statusMappings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_ImportLinearIssuesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ImportLinearIssuesResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}imported\0\u{1}skipped\0\u{1}failed\0\u{1}total\0\u{1}truncated\0\u{1}relations\0")

  fileprivate class _StorageClass {
    var _imported: UInt32 = 0
    var _skipped: UInt32 = 0
    var _failed: UInt32 = 0
    var _total: UInt32 = 0
    var _truncated: Bool = false
    var _relations: BriarAPI_LinearImportRelations? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _imported = source._imported
      _skipped = source._skipped
      _failed = source._failed
      _total = source._total
      _truncated = source._truncated
      _relations = source._relations
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt32Field(value: &_storage._imported) }()
        case 2: try { try decoder.decodeSingularUInt32Field(value: &_storage._skipped) }()
        case 3: try { try decoder.decodeSingularUInt32Field(value: &_storage._failed) }()
        case 4: try { try decoder.decodeSingularUInt32Field(value: &_storage._total) }()
        case 5: try { try decoder.decodeSingularBoolField(value: &_storage._truncated) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._relations) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._imported != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._imported, fieldNumber: 1)
      }
      if _storage._skipped != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._skipped, fieldNumber: 2)
      }
      if _storage._failed != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._failed, fieldNumber: 3)
      }
      if _storage._total != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._total, fieldNumber: 4)
      }
      if _storage._truncated != false {
        try visitor.visitSingularBoolField(value: _storage._truncated, fieldNumber: 5)
      }
      try { if let v = _storage._relations {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_ImportLinearIssuesResponse, rhs: BriarAPI_ImportLinearIssuesResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._imported != rhs_storage._imported {return false}
        if _storage._skipped != rhs_storage._skipped {return false}
        if _storage._failed != rhs_storage._failed {return false}
        if _storage._total != rhs_storage._total {return false}
        if _storage._truncated != rhs_storage._truncated {return false}
        if _storage._relations != rhs_storage._relations {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_LinearImportRelationCounter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LinearImportRelationCounter"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}linked\0\u{1}skipped\0\u{3}outside_scope\0\u{1}cycles\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.linked) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.skipped) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.outsideScope) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.cycles) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.linked != 0 {
      try visitor.visitSingularUInt32Field(value: self.linked, fieldNumber: 1)
    }
    if self.skipped != 0 {
      try visitor.visitSingularUInt32Field(value: self.skipped, fieldNumber: 2)
    }
    if self.outsideScope != 0 {
      try visitor.visitSingularUInt32Field(value: self.outsideScope, fieldNumber: 3)
    }
    if self.cycles != 0 {
      try visitor.visitSingularUInt32Field(value: self.cycles, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_LinearImportRelationCounter, rhs: BriarAPI_LinearImportRelationCounter) -> Bool {
    if lhs.linked != rhs.linked {return false}
    if lhs.skipped != rhs.skipped {return false}
    if lhs.outsideScope != rhs.outsideScope {return false}
    if lhs.cycles != rhs.cycles {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_LinearImportUnsupportedRelations: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LinearImportUnsupportedRelations"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}duplicate\0\u{1}similar\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.duplicate) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.similar) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.duplicate != 0 {
      try visitor.visitSingularUInt32Field(value: self.duplicate, fieldNumber: 1)
    }
    if self.similar != 0 {
      try visitor.visitSingularUInt32Field(value: self.similar, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_LinearImportUnsupportedRelations, rhs: BriarAPI_LinearImportUnsupportedRelations) -> Bool {
    if lhs.duplicate != rhs.duplicate {return false}
    if lhs.similar != rhs.similar {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BriarAPI_LinearImportRelations: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LinearImportRelations"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}hierarchy\0\u{1}related\0\u{1}dependencies\0\u{1}unsupported\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._hierarchy) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._related) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._dependencies) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._unsupported) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._hierarchy {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._related {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._dependencies {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._unsupported {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BriarAPI_LinearImportRelations, rhs: BriarAPI_LinearImportRelations) -> Bool {
    if lhs._hierarchy != rhs._hierarchy {return false}
    if lhs._related != rhs._related {return false}
    if lhs._dependencies != rhs._dependencies {return false}
    if lhs._unsupported != rhs._unsupported {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
