// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/organization.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol BriarAPI_OrganizationServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `listOrganizations`(request: BriarAPI_ListOrganizationsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListOrganizationsResponse>

    @available(iOS 13, *)
    func `createOrganization`(request: BriarAPI_CreateOrganizationRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateOrganizationResponse>

    @available(iOS 13, *)
    func `checkOrganizationHandleAvailability`(request: BriarAPI_CheckOrganizationHandleAvailabilityRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CheckOrganizationHandleAvailabilityResponse>

    @available(iOS 13, *)
    func `updateOrganization`(request: BriarAPI_UpdateOrganizationRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateOrganizationResponse>

    @available(iOS 13, *)
    func `updateOrganizationLogo`(request: BriarAPI_UpdateOrganizationLogoRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateOrganizationLogoResponse>

    @available(iOS 13, *)
    func `listOrganizationInvitations`(request: BriarAPI_ListOrganizationInvitationsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListOrganizationInvitationsResponse>

    @available(iOS 13, *)
    func `createOrganizationInvitation`(request: BriarAPI_CreateOrganizationInvitationRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateOrganizationInvitationResponse>

    @available(iOS 13, *)
    func `revokeOrganizationInvitation`(request: BriarAPI_RevokeOrganizationInvitationRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_RevokeOrganizationInvitationResponse>

    @available(iOS 13, *)
    func `getOrganizationInvitation`(request: BriarAPI_GetOrganizationInvitationRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetOrganizationInvitationResponse>

    @available(iOS 13, *)
    func `acceptOrganizationInvitation`(request: BriarAPI_AcceptOrganizationInvitationRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_AcceptOrganizationInvitationResponse>

    @available(iOS 13, *)
    func `listOrganizationMembers`(request: BriarAPI_ListOrganizationMembersRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListOrganizationMembersResponse>

    @available(iOS 13, *)
    func `updateOrganizationMemberRole`(request: BriarAPI_UpdateOrganizationMemberRoleRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateOrganizationMemberRoleResponse>

    @available(iOS 13, *)
    func `updateOrganizationMemberProjects`(request: BriarAPI_UpdateOrganizationMemberProjectsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateOrganizationMemberProjectsResponse>

    @available(iOS 13, *)
    func `removeOrganizationMember`(request: BriarAPI_RemoveOrganizationMemberRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_RemoveOrganizationMemberResponse>
}

/// Concrete implementation of `BriarAPI_OrganizationServiceClientInterface`.
public final class BriarAPI_OrganizationServiceClient: BriarAPI_OrganizationServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `listOrganizations`(request: BriarAPI_ListOrganizationsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListOrganizationsResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/ListOrganizations", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createOrganization`(request: BriarAPI_CreateOrganizationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateOrganizationResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/CreateOrganization", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `checkOrganizationHandleAvailability`(request: BriarAPI_CheckOrganizationHandleAvailabilityRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CheckOrganizationHandleAvailabilityResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/CheckOrganizationHandleAvailability", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateOrganization`(request: BriarAPI_UpdateOrganizationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateOrganizationResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/UpdateOrganization", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateOrganizationLogo`(request: BriarAPI_UpdateOrganizationLogoRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateOrganizationLogoResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/UpdateOrganizationLogo", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listOrganizationInvitations`(request: BriarAPI_ListOrganizationInvitationsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListOrganizationInvitationsResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/ListOrganizationInvitations", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createOrganizationInvitation`(request: BriarAPI_CreateOrganizationInvitationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateOrganizationInvitationResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/CreateOrganizationInvitation", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `revokeOrganizationInvitation`(request: BriarAPI_RevokeOrganizationInvitationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_RevokeOrganizationInvitationResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/RevokeOrganizationInvitation", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getOrganizationInvitation`(request: BriarAPI_GetOrganizationInvitationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetOrganizationInvitationResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/GetOrganizationInvitation", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `acceptOrganizationInvitation`(request: BriarAPI_AcceptOrganizationInvitationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_AcceptOrganizationInvitationResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/AcceptOrganizationInvitation", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listOrganizationMembers`(request: BriarAPI_ListOrganizationMembersRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListOrganizationMembersResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/ListOrganizationMembers", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateOrganizationMemberRole`(request: BriarAPI_UpdateOrganizationMemberRoleRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateOrganizationMemberRoleResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/UpdateOrganizationMemberRole", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateOrganizationMemberProjects`(request: BriarAPI_UpdateOrganizationMemberProjectsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateOrganizationMemberProjectsResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/UpdateOrganizationMemberProjects", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `removeOrganizationMember`(request: BriarAPI_RemoveOrganizationMemberRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_RemoveOrganizationMemberResponse> {
        return await self.client.unary(path: "/briar.app.v1.OrganizationService/RemoveOrganizationMember", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let listOrganizations = Connect.MethodSpec(name: "ListOrganizations", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let createOrganization = Connect.MethodSpec(name: "CreateOrganization", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let checkOrganizationHandleAvailability = Connect.MethodSpec(name: "CheckOrganizationHandleAvailability", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let updateOrganization = Connect.MethodSpec(name: "UpdateOrganization", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let updateOrganizationLogo = Connect.MethodSpec(name: "UpdateOrganizationLogo", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let listOrganizationInvitations = Connect.MethodSpec(name: "ListOrganizationInvitations", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let createOrganizationInvitation = Connect.MethodSpec(name: "CreateOrganizationInvitation", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let revokeOrganizationInvitation = Connect.MethodSpec(name: "RevokeOrganizationInvitation", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let getOrganizationInvitation = Connect.MethodSpec(name: "GetOrganizationInvitation", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let acceptOrganizationInvitation = Connect.MethodSpec(name: "AcceptOrganizationInvitation", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let listOrganizationMembers = Connect.MethodSpec(name: "ListOrganizationMembers", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let updateOrganizationMemberRole = Connect.MethodSpec(name: "UpdateOrganizationMemberRole", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let updateOrganizationMemberProjects = Connect.MethodSpec(name: "UpdateOrganizationMemberProjects", service: "briar.app.v1.OrganizationService", type: .unary)
            public static let removeOrganizationMember = Connect.MethodSpec(name: "RemoveOrganizationMember", service: "briar.app.v1.OrganizationService", type: .unary)
        }
    }
}
