// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/project.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol BriarAPI_ProjectServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `listProjects`(request: BriarAPI_ListProjectsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListProjectsResponse>

    @available(iOS 13, *)
    func `createProject`(request: BriarAPI_CreateProjectRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateProjectResponse>

    @available(iOS 13, *)
    func `deleteProject`(request: BriarAPI_DeleteProjectRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_DeleteProjectResponse>

    @available(iOS 13, *)
    func `updateProjectIcon`(request: BriarAPI_UpdateProjectIconRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateProjectIconResponse>

    @available(iOS 13, *)
    func `updateProjectIssueKeyPrefix`(request: BriarAPI_UpdateProjectIssueKeyPrefixRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateProjectIssueKeyPrefixResponse>

    @available(iOS 13, *)
    func `updateProjectTabs`(request: BriarAPI_UpdateProjectTabsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateProjectTabsResponse>

    @available(iOS 13, *)
    func `createProjectAgentToken`(request: BriarAPI_CreateProjectAgentTokenRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateProjectAgentTokenResponse>

    @available(iOS 13, *)
    func `updateProjectSettings`(request: BriarAPI_UpdateProjectSettingsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateProjectSettingsResponse>

    @available(iOS 13, *)
    func `updateCheckpointPolicy`(request: BriarAPI_UpdateCheckpointPolicyRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateCheckpointPolicyResponse>

    @available(iOS 13, *)
    func `getProjectExecutionWorkerPolicy`(request: BriarAPI_GetProjectExecutionWorkerPolicyRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetProjectExecutionWorkerPolicyResponse>

    @available(iOS 13, *)
    func `updateProjectExecutionWorkerPolicy`(request: BriarAPI_UpdateProjectExecutionWorkerPolicyRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateProjectExecutionWorkerPolicyResponse>

    @available(iOS 13, *)
    func `listTeamPlanningProjects`(request: BriarAPI_ListTeamPlanningProjectsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListTeamPlanningProjectsResponse>

    @available(iOS 13, *)
    func `createPlanningProject`(request: BriarAPI_CreatePlanningProjectRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreatePlanningProjectResponse>

    @available(iOS 13, *)
    func `updatePlanningProject`(request: BriarAPI_UpdatePlanningProjectRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdatePlanningProjectResponse>

    @available(iOS 13, *)
    func `moveIssueToPlanningProject`(request: BriarAPI_MoveIssueToPlanningProjectRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_MoveIssueToPlanningProjectResponse>

    @available(iOS 13, *)
    func `resolveIssueHierarchyLocation`(request: BriarAPI_ResolveIssueHierarchyLocationRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ResolveIssueHierarchyLocationResponse>
}

/// Concrete implementation of `BriarAPI_ProjectServiceClientInterface`.
public final class BriarAPI_ProjectServiceClient: BriarAPI_ProjectServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `listProjects`(request: BriarAPI_ListProjectsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListProjectsResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/ListProjects", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createProject`(request: BriarAPI_CreateProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateProjectResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/CreateProject", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `deleteProject`(request: BriarAPI_DeleteProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteProjectResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/DeleteProject", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateProjectIcon`(request: BriarAPI_UpdateProjectIconRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateProjectIconResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/UpdateProjectIcon", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateProjectIssueKeyPrefix`(request: BriarAPI_UpdateProjectIssueKeyPrefixRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateProjectIssueKeyPrefixResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/UpdateProjectIssueKeyPrefix", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateProjectTabs`(request: BriarAPI_UpdateProjectTabsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateProjectTabsResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/UpdateProjectTabs", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createProjectAgentToken`(request: BriarAPI_CreateProjectAgentTokenRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateProjectAgentTokenResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/CreateProjectAgentToken", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateProjectSettings`(request: BriarAPI_UpdateProjectSettingsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateProjectSettingsResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/UpdateProjectSettings", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateCheckpointPolicy`(request: BriarAPI_UpdateCheckpointPolicyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateCheckpointPolicyResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/UpdateCheckpointPolicy", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getProjectExecutionWorkerPolicy`(request: BriarAPI_GetProjectExecutionWorkerPolicyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetProjectExecutionWorkerPolicyResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/GetProjectExecutionWorkerPolicy", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateProjectExecutionWorkerPolicy`(request: BriarAPI_UpdateProjectExecutionWorkerPolicyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateProjectExecutionWorkerPolicyResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/UpdateProjectExecutionWorkerPolicy", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listTeamPlanningProjects`(request: BriarAPI_ListTeamPlanningProjectsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListTeamPlanningProjectsResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/ListTeamPlanningProjects", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createPlanningProject`(request: BriarAPI_CreatePlanningProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreatePlanningProjectResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/CreatePlanningProject", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updatePlanningProject`(request: BriarAPI_UpdatePlanningProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdatePlanningProjectResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/UpdatePlanningProject", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `moveIssueToPlanningProject`(request: BriarAPI_MoveIssueToPlanningProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_MoveIssueToPlanningProjectResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/MoveIssueToPlanningProject", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `resolveIssueHierarchyLocation`(request: BriarAPI_ResolveIssueHierarchyLocationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ResolveIssueHierarchyLocationResponse> {
        return await self.client.unary(path: "/briar.app.v1.ProjectService/ResolveIssueHierarchyLocation", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let listProjects = Connect.MethodSpec(name: "ListProjects", service: "briar.app.v1.ProjectService", type: .unary)
            public static let createProject = Connect.MethodSpec(name: "CreateProject", service: "briar.app.v1.ProjectService", type: .unary)
            public static let deleteProject = Connect.MethodSpec(name: "DeleteProject", service: "briar.app.v1.ProjectService", type: .unary)
            public static let updateProjectIcon = Connect.MethodSpec(name: "UpdateProjectIcon", service: "briar.app.v1.ProjectService", type: .unary)
            public static let updateProjectIssueKeyPrefix = Connect.MethodSpec(name: "UpdateProjectIssueKeyPrefix", service: "briar.app.v1.ProjectService", type: .unary)
            public static let updateProjectTabs = Connect.MethodSpec(name: "UpdateProjectTabs", service: "briar.app.v1.ProjectService", type: .unary)
            public static let createProjectAgentToken = Connect.MethodSpec(name: "CreateProjectAgentToken", service: "briar.app.v1.ProjectService", type: .unary)
            public static let updateProjectSettings = Connect.MethodSpec(name: "UpdateProjectSettings", service: "briar.app.v1.ProjectService", type: .unary)
            public static let updateCheckpointPolicy = Connect.MethodSpec(name: "UpdateCheckpointPolicy", service: "briar.app.v1.ProjectService", type: .unary)
            public static let getProjectExecutionWorkerPolicy = Connect.MethodSpec(name: "GetProjectExecutionWorkerPolicy", service: "briar.app.v1.ProjectService", type: .unary)
            public static let updateProjectExecutionWorkerPolicy = Connect.MethodSpec(name: "UpdateProjectExecutionWorkerPolicy", service: "briar.app.v1.ProjectService", type: .unary)
            public static let listTeamPlanningProjects = Connect.MethodSpec(name: "ListTeamPlanningProjects", service: "briar.app.v1.ProjectService", type: .unary)
            public static let createPlanningProject = Connect.MethodSpec(name: "CreatePlanningProject", service: "briar.app.v1.ProjectService", type: .unary)
            public static let updatePlanningProject = Connect.MethodSpec(name: "UpdatePlanningProject", service: "briar.app.v1.ProjectService", type: .unary)
            public static let moveIssueToPlanningProject = Connect.MethodSpec(name: "MoveIssueToPlanningProject", service: "briar.app.v1.ProjectService", type: .unary)
            public static let resolveIssueHierarchyLocation = Connect.MethodSpec(name: "ResolveIssueHierarchyLocation", service: "briar.app.v1.ProjectService", type: .unary)
        }
    }
}
