// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/team.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol BriarAPI_TeamServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `listTeams`(request: BriarAPI_ListTeamsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListTeamsResponse>

    @available(iOS 13, *)
    func `createTeam`(request: BriarAPI_CreateTeamRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateTeamResponse>

    @available(iOS 13, *)
    func `deleteTeam`(request: BriarAPI_DeleteTeamRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_DeleteTeamResponse>

    @available(iOS 13, *)
    func `updateTeamIcon`(request: BriarAPI_UpdateTeamIconRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateTeamIconResponse>

    @available(iOS 13, *)
    func `updateTeamIssueKeyPrefix`(request: BriarAPI_UpdateTeamIssueKeyPrefixRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateTeamIssueKeyPrefixResponse>

    @available(iOS 13, *)
    func `updateTeamTabs`(request: BriarAPI_UpdateTeamTabsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateTeamTabsResponse>

    @available(iOS 13, *)
    func `createTeamAgentToken`(request: BriarAPI_CreateTeamAgentTokenRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreateTeamAgentTokenResponse>

    @available(iOS 13, *)
    func `updateTeamSettings`(request: BriarAPI_UpdateTeamSettingsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateTeamSettingsResponse>

    @available(iOS 13, *)
    func `updateCheckpointPolicy`(request: BriarAPI_UpdateCheckpointPolicyRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateCheckpointPolicyResponse>

    @available(iOS 13, *)
    func `getTeamExecutionWorkerPolicy`(request: BriarAPI_GetTeamExecutionWorkerPolicyRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_GetTeamExecutionWorkerPolicyResponse>

    @available(iOS 13, *)
    func `updateTeamExecutionWorkerPolicy`(request: BriarAPI_UpdateTeamExecutionWorkerPolicyRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdateTeamExecutionWorkerPolicyResponse>

    @available(iOS 13, *)
    func `listTeamPlanningProjects`(request: BriarAPI_ListTeamPlanningProjectsRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ListTeamPlanningProjectsResponse>

    @available(iOS 13, *)
    func `createPlanningProject`(request: BriarAPI_CreatePlanningProjectRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_CreatePlanningProjectResponse>

    @available(iOS 13, *)
    func `updatePlanningProject`(request: BriarAPI_UpdatePlanningProjectRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_UpdatePlanningProjectResponse>

    @available(iOS 13, *)
    func `deletePlanningProject`(request: BriarAPI_DeletePlanningProjectRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_DeletePlanningProjectResponse>

    @available(iOS 13, *)
    func `moveIssueToPlanningProject`(request: BriarAPI_MoveIssueToPlanningProjectRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_MoveIssueToPlanningProjectResponse>

    @available(iOS 13, *)
    func `resolveIssueHierarchyLocation`(request: BriarAPI_ResolveIssueHierarchyLocationRequest, headers: Connect.Headers) async -> ResponseMessage<BriarAPI_ResolveIssueHierarchyLocationResponse>
}

/// Concrete implementation of `BriarAPI_TeamServiceClientInterface`.
public final class BriarAPI_TeamServiceClient: BriarAPI_TeamServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `listTeams`(request: BriarAPI_ListTeamsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListTeamsResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/ListTeams", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createTeam`(request: BriarAPI_CreateTeamRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateTeamResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/CreateTeam", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `deleteTeam`(request: BriarAPI_DeleteTeamRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteTeamResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/DeleteTeam", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateTeamIcon`(request: BriarAPI_UpdateTeamIconRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateTeamIconResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/UpdateTeamIcon", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateTeamIssueKeyPrefix`(request: BriarAPI_UpdateTeamIssueKeyPrefixRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateTeamIssueKeyPrefixResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/UpdateTeamIssueKeyPrefix", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateTeamTabs`(request: BriarAPI_UpdateTeamTabsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateTeamTabsResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/UpdateTeamTabs", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createTeamAgentToken`(request: BriarAPI_CreateTeamAgentTokenRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateTeamAgentTokenResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/CreateTeamAgentToken", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateTeamSettings`(request: BriarAPI_UpdateTeamSettingsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateTeamSettingsResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/UpdateTeamSettings", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateCheckpointPolicy`(request: BriarAPI_UpdateCheckpointPolicyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateCheckpointPolicyResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/UpdateCheckpointPolicy", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getTeamExecutionWorkerPolicy`(request: BriarAPI_GetTeamExecutionWorkerPolicyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetTeamExecutionWorkerPolicyResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/GetTeamExecutionWorkerPolicy", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateTeamExecutionWorkerPolicy`(request: BriarAPI_UpdateTeamExecutionWorkerPolicyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateTeamExecutionWorkerPolicyResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/UpdateTeamExecutionWorkerPolicy", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listTeamPlanningProjects`(request: BriarAPI_ListTeamPlanningProjectsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListTeamPlanningProjectsResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/ListTeamPlanningProjects", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `createPlanningProject`(request: BriarAPI_CreatePlanningProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreatePlanningProjectResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/CreatePlanningProject", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updatePlanningProject`(request: BriarAPI_UpdatePlanningProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdatePlanningProjectResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/UpdatePlanningProject", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `deletePlanningProject`(request: BriarAPI_DeletePlanningProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeletePlanningProjectResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/DeletePlanningProject", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `moveIssueToPlanningProject`(request: BriarAPI_MoveIssueToPlanningProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_MoveIssueToPlanningProjectResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/MoveIssueToPlanningProject", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `resolveIssueHierarchyLocation`(request: BriarAPI_ResolveIssueHierarchyLocationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ResolveIssueHierarchyLocationResponse> {
        return await self.client.unary(path: "/briar.app.v1.TeamService/ResolveIssueHierarchyLocation", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let listTeams = Connect.MethodSpec(name: "ListTeams", service: "briar.app.v1.TeamService", type: .unary)
            public static let createTeam = Connect.MethodSpec(name: "CreateTeam", service: "briar.app.v1.TeamService", type: .unary)
            public static let deleteTeam = Connect.MethodSpec(name: "DeleteTeam", service: "briar.app.v1.TeamService", type: .unary)
            public static let updateTeamIcon = Connect.MethodSpec(name: "UpdateTeamIcon", service: "briar.app.v1.TeamService", type: .unary)
            public static let updateTeamIssueKeyPrefix = Connect.MethodSpec(name: "UpdateTeamIssueKeyPrefix", service: "briar.app.v1.TeamService", type: .unary)
            public static let updateTeamTabs = Connect.MethodSpec(name: "UpdateTeamTabs", service: "briar.app.v1.TeamService", type: .unary)
            public static let createTeamAgentToken = Connect.MethodSpec(name: "CreateTeamAgentToken", service: "briar.app.v1.TeamService", type: .unary)
            public static let updateTeamSettings = Connect.MethodSpec(name: "UpdateTeamSettings", service: "briar.app.v1.TeamService", type: .unary)
            public static let updateCheckpointPolicy = Connect.MethodSpec(name: "UpdateCheckpointPolicy", service: "briar.app.v1.TeamService", type: .unary)
            public static let getTeamExecutionWorkerPolicy = Connect.MethodSpec(name: "GetTeamExecutionWorkerPolicy", service: "briar.app.v1.TeamService", type: .unary)
            public static let updateTeamExecutionWorkerPolicy = Connect.MethodSpec(name: "UpdateTeamExecutionWorkerPolicy", service: "briar.app.v1.TeamService", type: .unary)
            public static let listTeamPlanningProjects = Connect.MethodSpec(name: "ListTeamPlanningProjects", service: "briar.app.v1.TeamService", type: .unary)
            public static let createPlanningProject = Connect.MethodSpec(name: "CreatePlanningProject", service: "briar.app.v1.TeamService", type: .unary)
            public static let updatePlanningProject = Connect.MethodSpec(name: "UpdatePlanningProject", service: "briar.app.v1.TeamService", type: .unary)
            public static let deletePlanningProject = Connect.MethodSpec(name: "DeletePlanningProject", service: "briar.app.v1.TeamService", type: .unary)
            public static let moveIssueToPlanningProject = Connect.MethodSpec(name: "MoveIssueToPlanningProject", service: "briar.app.v1.TeamService", type: .unary)
            public static let resolveIssueHierarchyLocation = Connect.MethodSpec(name: "ResolveIssueHierarchyLocation", service: "briar.app.v1.TeamService", type: .unary)
        }
    }
}
