-- Carry DM and channel attachments onto the issue an approved proposal
-- creates, and let those files keep their own types.
--
-- Run a98bf275-d5d6-5e66-aa5f-89e77a4ca34a blocked on
-- missing-source-attachments: the user had attached two Markdown files to the
-- DM the Agent turned into an issue, and the created run carried none of them.
-- Two things were in the way. briar_issue_attachments accepted only image,
-- text/html and video types, so a Markdown or PDF source file could not be
-- stored at all; and the guard triggers below pinned every channel-approved
-- run to `attachmentCount = 0`, which is what made "no attachments" the only
-- legal outcome rather than an accident of the write path.
--
-- Row cost: briar_issue_attachments held 387 rows in production on 2026-09-09
-- and nothing foreign-keys into it, so the rebuild parks and restores those
-- 387 rows and reaches no descendant. Two indexes and two sync triggers are
-- recreated after the restore, plus the two briar_hunt_runs guard triggers
-- this migration rewrites. Well under 1,200 rows written in total.
--
-- Generated by scripts/generate-issue-attachment-sources-migration.ts.

-- Widen briar_issue_attachments.content_type to the union with the channel
-- composer's allowlist, so a file a user attached in a DM can be stored
-- against the issue that DM produced. A leaf table with no foreign-key
-- descendants, so the drop cascades nowhere; its own indexes and triggers go
-- with it and are recreated below.
pragma defer_foreign_keys = on;

create table briar_issue_attachment_type_backup as
select * from briar_issue_attachments;

drop table briar_issue_attachments;

CREATE TABLE briar_issue_attachments (
  id text primary key not null,
  run_id text not null references briar_hunt_runs (id) on delete cascade,
  project_id text not null references briar_projects (id) on delete cascade,
  object_key text not null unique check (
    object_key = trim(object_key)
    and length(object_key) between 1 and 500
  ),
  filename text not null check (length(trim(filename)) between 1 and 255),
  content_type text not null check (content_type in (
    'image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/avif',
    'image/svg+xml', 'text/html', 'video/mp4', 'video/webm', 'video/quicktime',
    'application/pdf', 'text/markdown', 'text/plain'
  )),
  byte_size integer not null check (byte_size between 1 and 20971520),
  created_at text not null
);

insert into briar_issue_attachments
select * from briar_issue_attachment_type_backup;

drop table briar_issue_attachment_type_backup;

CREATE INDEX briar_issue_attachments_run_idx
  on briar_issue_attachments (run_id, created_at, id);

CREATE INDEX briar_issue_attachments_project_idx
  on briar_issue_attachments (project_id, run_id);

CREATE TRIGGER briar_dashboard_attachments_insert_sync
after insert on briar_issue_attachments BEGIN
  insert into briar_dashboard_changes (
    project_id, entity_type, entity_id, operation, created_at
  ) values (new.project_id, 'run', new.run_id, 'upsert', datetime('now'));
  insert into briar_dashboard_sync_state (project_id, current_version)
  values (new.project_id, last_insert_rowid())
  on conflict (project_id) do update set current_version = excluded.current_version;
END;

CREATE TRIGGER briar_dashboard_attachments_delete_sync
after delete on briar_issue_attachments BEGIN
  insert into briar_dashboard_changes (
    project_id, entity_type, entity_id, operation, created_at
  ) values (old.project_id, 'run', old.run_id, 'upsert', datetime('now'));
  insert into briar_dashboard_sync_state (project_id, current_version)
  values (old.project_id, last_insert_rowid())
  on conflict (project_id) do update set current_version = excluded.current_version;
END;

pragma defer_foreign_keys = off;

-- Teach the two guards that assert "the created run is exactly what was
-- approved" about the payload's fourth key. They are reproduced verbatim from
-- the schema snapshot apart from the two clauses named above; every other
-- assertion is unchanged.

drop trigger if exists "briar_hunt_runs_channel_proposal_reservation_required";

CREATE TRIGGER briar_hunt_runs_channel_proposal_reservation_required
before insert on briar_hunt_runs
when new.source = 'issue'
  and new.source_key like 'briar-channel-approved:%'
  and not exists (
    select 1 from briar_hunt_runs existing
    where existing.project_id = new.project_id
      and existing.source = new.source
      and existing.source_key = new.source_key
  )
  and not exists (
    select 1
    from briar_channel_action_proposals proposal
    join briar_channels channel on channel.id = proposal.channel_id
    join briar_projects project
      on project.id = proposal.project_id
     and project.organization_id = channel.organization_id
    where proposal.status = 'pending'
      and proposal.action_type = 'request_issue_create'
      and proposal.project_id = new.project_id
      and proposal.issue_source_key = new.source_key
      and proposal.accepted_by_user_id is not null
      and proposal.accepted_at is not null
      and (
        length(new.source_key) = 87
        and substr(new.source_key, 1, 23) = 'briar-channel-approved:'
        and substr(new.source_key, 24) not glob '*[^0-9a-f]*'
      )
      and (
        json_type(proposal.payload_json) = 'object'
        and (select count(*) from json_each(proposal.payload_json)) = 1
        and json_type(proposal.payload_json, '$.issue') = 'object'
        and (
          select count(*)
          from json_each(proposal.payload_json, '$.issue')
        ) in (3, 4)
        and (
          (
            select count(*)
            from json_each(proposal.payload_json, '$.issue')
          ) = 3
          or json_type(
            proposal.payload_json, '$.issue.attachmentIds'
          ) = 'array'
        )
        and json_type(proposal.payload_json, '$.issue.title') = 'text'
        and json_type(
          proposal.payload_json, '$.issue.description'
        ) in ('text', 'null')
        and json_type(
          proposal.payload_json, '$.issue.priority'
        ) in ('integer', 'null')
      )
      and (
        new.title = json_extract(proposal.payload_json, '$.issue.title')
        and new.issue_description is
          json_extract(proposal.payload_json, '$.issue.description')
        and new.priority is
          json_extract(proposal.payload_json, '$.issue.priority')
        and new.status = 'backlog'
        and new.stage = 'queued'
        and new.workflow_stage is null
        and new.issue_checkpoints_json = '[]'
        and new.detail =
          '채널 대화에서 사용자가 승인한 제안으로 생성된 이슈입니다.'
        and new.repository = coalesce(
          (select settings.github_repository
           from briar_project_settings settings
           where settings.project_id = proposal.project_id),
          project.name
        )
      )
      and (
        new.assignee_user_id is null
        and new.agent_id is null
        and new.worker_id is null
        and new.requested_worker_id is null
        and new.claim_token_hash is null
        and new.claimed_by is null
        and new.claimed_at is null
        and new.lease_expires_at is null
        and new.claim_attempts = 0
        and new.current_attempt = 1
        and new.current_revision = 1
        and new.full_auto = 0
        and new.requires_claim_token = 0
      )
      and (
        new.last_execution_id is null
        and new.dispatch_mode is null
        and new.dispatch_request_id is null
        and new.dispatched_at is null
        and new.requested_by_user_id is null
        and new.requested_agent_provider is null
        and new.requested_agent_model is null
        and new.requested_agent_effort is null
        and new.preferred_agent_provider is null
        and new.preferred_agent_model is null
        and new.preferred_agent_effort is null
      )
      and (
        new.branch is null
        and new.commit_sha is null
        and new.tracker_provider is null
        and new.tracker_issue_id is null
        and new.tracker_issue_identifier is null
        and new.tracker_issue_url is null
        and new.tracker_issue_state is null
        and new.result_summary is null
        and new.structured_result_json is null
        and new.pull_request_urls = '[]'
        and new.target_sha is null
        and new.staging_qa_status is null
        and new.production_qa_status is null
        and new.staging_qa_detail is null
        and new.production_qa_detail is null
        and new.execution_metrics_json is null
      )
      and (
        new.completed_at is null
        and new.paused_at is null
        and new.resume_requested_at is null
        and new.waiting_checkpoint_key is null
        and new.waiting_checkpoint_revision is null
        and new.event_count = 0
        and new.source_created_at = proposal.created_at
        and new.started_at = proposal.created_at
        and new.last_event_at = proposal.created_at
        and new.created_at = new.updated_at
      )
      and (
        json_type(new.context_json) = 'object'
        and (select count(*) from json_each(new.context_json)) = 6
        and json_type(new.context_json, '$.origin') = 'text'
        and json_extract(new.context_json, '$.origin') = 'briar-channel'
        and json_type(new.context_json, '$.proposalId') = 'text'
        and json_extract(new.context_json, '$.proposalId') = proposal.id
        and json_type(new.context_json, '$.channelId') = 'text'
        and json_extract(new.context_json, '$.channelId') = proposal.channel_id
        and json_type(new.context_json, '$.issueId') = 'text'
        and json_extract(new.context_json, '$.issueId') = proposal.id
        and json_type(new.context_json, '$.attachmentCount') = 'integer'
        and json_extract(new.context_json, '$.attachmentCount')
          = coalesce(
            json_array_length(proposal.payload_json, '$.issue.attachmentIds'),
            0
          )
        and json_type(new.context_json, '$.relatedMessage') = 'object'
        and (
          select count(*)
          from json_each(new.context_json, '$.relatedMessage')
        ) = 4
        and json_type(
          new.context_json, '$.relatedMessage.organizationId'
        ) = 'text'
        and json_extract(
          new.context_json, '$.relatedMessage.organizationId'
        ) = channel.organization_id
        and json_type(
          new.context_json, '$.relatedMessage.channelId'
        ) = 'text'
        and json_extract(
          new.context_json, '$.relatedMessage.channelId'
        ) = proposal.channel_id
        and json_type(
          new.context_json, '$.relatedMessage.messageId'
        ) = 'text'
        and json_extract(
          new.context_json, '$.relatedMessage.messageId'
        ) = proposal.reply_message_id
        and json_type(
          new.context_json, '$.relatedMessage.rootMessageId'
        ) = 'text'
      )
  )
BEGIN
  select raise(abort, 'channel proposal approval reservation not found');
END;

drop trigger if exists "briar_hunt_runs_finalize_channel_proposal_approval";

CREATE TRIGGER briar_hunt_runs_finalize_channel_proposal_approval
after insert on briar_hunt_runs
when new.source = 'issue'
  and new.source_key like 'briar-channel-approved:%'
  and exists (
    select 1
    from briar_channel_action_proposals proposal
    join briar_channels channel on channel.id = proposal.channel_id
    join briar_projects project
      on project.id = proposal.project_id
     and project.organization_id = channel.organization_id
    where proposal.status = 'pending'
      and proposal.action_type = 'request_issue_create'
      and proposal.project_id = new.project_id
      and proposal.issue_source_key = new.source_key
      and proposal.accepted_by_user_id is not null
      and proposal.accepted_at is not null
      and (
        length(new.source_key) = 87
        and substr(new.source_key, 1, 23) = 'briar-channel-approved:'
        and substr(new.source_key, 24) not glob '*[^0-9a-f]*'
      )
      and (
        json_type(proposal.payload_json) = 'object'
        and (select count(*) from json_each(proposal.payload_json)) = 1
        and json_type(proposal.payload_json, '$.issue') = 'object'
        and (
          select count(*)
          from json_each(proposal.payload_json, '$.issue')
        ) in (3, 4)
        and (
          (
            select count(*)
            from json_each(proposal.payload_json, '$.issue')
          ) = 3
          or json_type(
            proposal.payload_json, '$.issue.attachmentIds'
          ) = 'array'
        )
        and json_type(proposal.payload_json, '$.issue.title') = 'text'
        and json_type(
          proposal.payload_json, '$.issue.description'
        ) in ('text', 'null')
        and json_type(
          proposal.payload_json, '$.issue.priority'
        ) in ('integer', 'null')
      )
      and (
        new.title = json_extract(proposal.payload_json, '$.issue.title')
        and new.issue_description is
          json_extract(proposal.payload_json, '$.issue.description')
        and new.priority is
          json_extract(proposal.payload_json, '$.issue.priority')
        and new.status = 'backlog'
        and new.stage = 'queued'
        and new.workflow_stage is null
        and new.issue_checkpoints_json = '[]'
        and new.detail =
          '채널 대화에서 사용자가 승인한 제안으로 생성된 이슈입니다.'
        and new.repository = coalesce(
          (select settings.github_repository
           from briar_project_settings settings
           where settings.project_id = proposal.project_id),
          project.name
        )
      )
      and (
        new.assignee_user_id is null
        and new.agent_id is null
        and new.worker_id is null
        and new.requested_worker_id is null
        and new.claim_token_hash is null
        and new.claimed_by is null
        and new.claimed_at is null
        and new.lease_expires_at is null
        and new.claim_attempts = 0
        and new.current_attempt = 1
        and new.current_revision = 1
        and new.full_auto = 0
        and new.requires_claim_token = 0
      )
      and (
        new.last_execution_id is null
        and new.dispatch_mode is null
        and new.dispatch_request_id is null
        and new.dispatched_at is null
        and new.requested_by_user_id is null
        and new.requested_agent_provider is null
        and new.requested_agent_model is null
        and new.requested_agent_effort is null
        and new.preferred_agent_provider is null
        and new.preferred_agent_model is null
        and new.preferred_agent_effort is null
      )
      and (
        new.branch is null
        and new.commit_sha is null
        and new.tracker_provider is null
        and new.tracker_issue_id is null
        and new.tracker_issue_identifier is null
        and new.tracker_issue_url is null
        and new.tracker_issue_state is null
        and new.result_summary is null
        and new.structured_result_json is null
        and new.pull_request_urls = '[]'
        and new.target_sha is null
        and new.staging_qa_status is null
        and new.production_qa_status is null
        and new.staging_qa_detail is null
        and new.production_qa_detail is null
        and new.execution_metrics_json is null
      )
      and (
        new.completed_at is null
        and new.paused_at is null
        and new.resume_requested_at is null
        and new.waiting_checkpoint_key is null
        and new.waiting_checkpoint_revision is null
        and new.event_count = 0
        and new.source_created_at = proposal.created_at
        and new.started_at = proposal.created_at
        and new.last_event_at = proposal.created_at
        and new.created_at = new.updated_at
      )
      and (
        json_type(new.context_json) = 'object'
        and (select count(*) from json_each(new.context_json)) = 6
        and json_type(new.context_json, '$.origin') = 'text'
        and json_extract(new.context_json, '$.origin') = 'briar-channel'
        and json_type(new.context_json, '$.proposalId') = 'text'
        and json_extract(new.context_json, '$.proposalId') = proposal.id
        and json_type(new.context_json, '$.channelId') = 'text'
        and json_extract(new.context_json, '$.channelId') = proposal.channel_id
        and json_type(new.context_json, '$.issueId') = 'text'
        and json_extract(new.context_json, '$.issueId') = proposal.id
        and json_type(new.context_json, '$.attachmentCount') = 'integer'
        and json_extract(new.context_json, '$.attachmentCount')
          = coalesce(
            json_array_length(proposal.payload_json, '$.issue.attachmentIds'),
            0
          )
        and json_type(new.context_json, '$.relatedMessage') = 'object'
        and (
          select count(*)
          from json_each(new.context_json, '$.relatedMessage')
        ) = 4
        and json_type(
          new.context_json, '$.relatedMessage.organizationId'
        ) = 'text'
        and json_extract(
          new.context_json, '$.relatedMessage.organizationId'
        ) = channel.organization_id
        and json_type(
          new.context_json, '$.relatedMessage.channelId'
        ) = 'text'
        and json_extract(
          new.context_json, '$.relatedMessage.channelId'
        ) = proposal.channel_id
        and json_type(
          new.context_json, '$.relatedMessage.messageId'
        ) = 'text'
        and json_extract(
          new.context_json, '$.relatedMessage.messageId'
        ) = proposal.reply_message_id
        and json_type(
          new.context_json, '$.relatedMessage.rootMessageId'
        ) = 'text'
      )
  )
BEGIN
  insert into briar_channel_issue_approval_audit (
    id, proposal_id, organization_id, channel_id, project_id, run_id,
    approved_by_user_id, approved_at, issue_source_key, result_verification,
    payload_json, created_at
  )
  select proposal.id || ':approval:' || proposal.issue_source_key,
         proposal.id, channel.organization_id, proposal.channel_id,
         proposal.project_id, new.id, proposal.accepted_by_user_id,
         proposal.accepted_at, proposal.issue_source_key, 'atomic',
         proposal.payload_json, proposal.accepted_at
  from briar_channel_action_proposals proposal
  join briar_channels channel on channel.id = proposal.channel_id
  where proposal.status = 'pending'
    and proposal.action_type = 'request_issue_create'
    and proposal.project_id = new.project_id
    and proposal.issue_source_key = new.source_key
    and proposal.accepted_by_user_id is not null
    and proposal.accepted_at is not null;
  update briar_channel_action_proposals
  set status = 'accepted', result_run_id = new.id, updated_at = accepted_at
  where status = 'pending' and action_type = 'request_issue_create'
    and project_id = new.project_id and issue_source_key = new.source_key
    and accepted_by_user_id is not null and accepted_at is not null;
END;
