import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

/**
 * Embed the reviewed provider-runtime manifest, its lockfile, and the pinned
 * Bun/Node versions into the CLI so `briar sandbox up` can build the sandbox
 * image from any installed CLI without a checkout of this repository.
 */
const root = resolve(import.meta.dir, "..");
const target = resolve(root, "apps/briar/src-cli/sandbox-runtime-assets.ts");
const runtimeDirectory = resolve(
  root,
  "infrastructure/managed-computers/provider-runtime",
);
const lockPath = resolve(root, "infrastructure/managed-computers/image-lock.env");

const lockValues = Object.fromEntries(
  (await readFile(lockPath, "utf8"))
    .split("\n")
    .filter((line) => line.length > 0 && !line.startsWith("#"))
    .map((line) => {
      const separator = line.indexOf("=");
      return [line.slice(0, separator), line.slice(separator + 1)];
    }),
);
const requiredLock = (name: string) => {
  const value = lockValues[name];
  if (!value || !/^[0-9]+\.[0-9]+\.[0-9]+$/u.test(value)) {
    throw new Error(`${name} must be a pinned semantic version in image-lock.env`);
  }
  return value;
};

const assets = {
  bunVersion: requiredLock("BUN_VERSION"),
  nodeVersion: requiredLock("NODE_VERSION"),
  providerRuntimePackageJson: await readFile(
    resolve(runtimeDirectory, "package.json"),
    "utf8",
  ),
  providerRuntimeBunLock: await readFile(
    resolve(runtimeDirectory, "bun.lock"),
    "utf8",
  ),
};
const output = `// Generated by scripts/generate-sandbox-runtime-assets.ts. Do not edit.
export const sandboxRuntimeAssets = ${JSON.stringify(assets, null, 2)} as const;
`;

if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== output) {
    console.error(
      "Sandbox runtime assets are stale. Run: bun run sandbox:generate",
    );
    process.exitCode = 1;
  }
} else {
  await writeFile(target, output);
}
