import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const target = resolve(root, "apps/briar/src-cli/bundled-skill-guides.ts");
const sources = [
  {
    name: "briar-workflow",
    description: "Execute and track repository work through a Briar workflow.",
    path: resolve(root, "apps/briar/src-cli/guides/briar-workflow.md"),
  },
  {
    name: "browser",
    description: "Verify interfaces and capture result evidence with an agent browser.",
    path: resolve(root, "apps/briar/src-cli/guides/browser.md"),
  },
];

const guides = await Promise.all(
  sources.map(async ({ path: _path, ...metadata }) => ({
    ...metadata,
    markdown: await readFile(_path, "utf8"),
  })),
);
const output = `// Generated by scripts/generate-skill-guides.ts. Do not edit.
export const bundledSkillGuides = ${JSON.stringify(guides, null, 2)} as const;
`;

if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== output) {
    console.error("Bundled skill guides are stale. Run: bun run skills:generate");
    process.exitCode = 1;
  }
} else {
  await writeFile(target, output);
}
