import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

/**
 * Embed the reviewed provider-runtime manifest, its lockfile, and the pinned
 * Bun/Node versions into the CLI so `briar sandbox up` can build the sandbox
 * image from any installed CLI without a checkout of this repository.
 */
const root = resolve(import.meta.dir, "..");
const target = resolve(root, "apps/briar/src-cli/sandbox-runtime-assets.ts");
const runtimeDirectory = resolve(
  root,
  "infrastructure/managed-computers/provider-runtime",
);
const lockPath = resolve(root, "infrastructure/managed-computers/image-lock.env");

const lockValues = Object.fromEntries(
  (await readFile(lockPath, "utf8"))
    .split("\n")
    .filter((line) => line.length > 0 && !line.startsWith("#"))
    .map((line) => {
      const separator = line.indexOf("=");
      return [line.slice(0, separator), line.slice(separator + 1)];
    }),
);
const requiredLock = (name: string) => {
  const value = lockValues[name];
  if (value === undefined) {
    throw new Error(`${name} is missing from image-lock.env`);
  }
  if (!/^[0-9]+\.[0-9]+\.[0-9]+$/u.test(value)) {
    throw new Error(
      `${name} must be a pinned semantic version in image-lock.env, not ${value}`,
    );
  }
  return value;
};
/**
 * A checksum the sandbox Dockerfile verifies a downloaded binary against. It
 * is embedded verbatim in the build context, so an unpinned or malformed
 * value has to fail here rather than inside `docker build`.
 */
const requiredSha256 = (name: string) => {
  const value = lockValues[name];
  if (value === undefined) {
    throw new Error(`${name} is missing from image-lock.env`);
  }
  if (!/^[0-9a-f]{64}$/u.test(value)) {
    throw new Error(
      `${name} must be a lowercase 64-character SHA-256 in image-lock.env, not ${value}`,
    );
  }
  return value;
};

const managedDirectory = resolve(root, "infrastructure/managed-computers");
/**
 * Display and Computer Use files shared with the managed-computer image. They
 * are copied verbatim into the sandbox image so both environments run the
 * same desktop session, browser launcher, and input executor.
 */
const desktopFileNames = [
  "briar-remote-desktop",
  "briar-computer-use-window",
  "briar-open-browser",
  "briar-computer-executor.py",
  "xfce4-helpers.rc",
  "xfce4-terminalrc",
  "mimeapps.list",
  "briar-google-chrome.desktop",
  "remote-desktop-packages.txt",
] as const;
const desktopFiles = Object.fromEntries(
  await Promise.all(desktopFileNames.map(async (name) =>
    [name, await readFile(resolve(managedDirectory, name), "utf8")] as const
  )),
);

const assets = {
  bunVersion: requiredLock("BUN_VERSION"),
  nodeVersion: requiredLock("NODE_VERSION"),
  /**
   * Standalone provider CLIs the sandbox image downloads directly. OpenCode
   * ships a lifecycle-script npm package the image must not run, and Grok has
   * no npm package at all, so both are pinned releases verified per
   * architecture exactly like the managed-computer AMI does.
   */
  opencodeCli: {
    version: requiredLock("OPENCODE_CLI_VERSION"),
    sha256: {
      amd64: requiredSha256("OPENCODE_CLI_LINUX_X64_SHA256"),
      arm64: requiredSha256("OPENCODE_CLI_LINUX_ARM64_SHA256"),
    },
  },
  grokCli: {
    version: requiredLock("GROK_CLI_VERSION"),
    sha256: {
      amd64: requiredSha256("GROK_CLI_LINUX_X64_SHA256"),
      arm64: requiredSha256("GROK_CLI_LINUX_AARCH64_SHA256"),
    },
  },
  desktopFiles,
  providerRuntimePackageJson: await readFile(
    resolve(runtimeDirectory, "package.json"),
    "utf8",
  ),
  providerRuntimeBunLock: await readFile(
    resolve(runtimeDirectory, "bun.lock"),
    "utf8",
  ),
};
const output = `// Generated by scripts/generate-sandbox-runtime-assets.ts. Do not edit.
export const sandboxRuntimeAssets = ${JSON.stringify(assets, null, 2)} as const;
`;

if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== output) {
    console.error(
      "Sandbox runtime assets are stale. Run: bun run sandbox:generate",
    );
    process.exitCode = 1;
  }
} else {
  await writeFile(target, output);
}
