// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/account.proto
//

import BriarContracts
import Connect
import Foundation
import SwiftProtobuf

/// Mock implementation of `BriarAPI_AccountServiceClientInterface`.
///
/// Production implementations can be substituted with instances of this
/// class to mock RPC calls. Behavior can be customized
/// either through the properties on this class or by
/// subclassing the mock and overriding its methods.
///
/// Note: This class does not handle thread-safe locking, but provides
/// `@unchecked Sendable` conformance to simplify testing and mocking.
@available(iOS 13, *)
open class BriarAPI_AccountServiceClientMock: BriarAPI_AccountServiceClientInterface, @unchecked Sendable {
    /// Mocked for async calls to `getCurrentUser()`.
    public var mockAsyncGetCurrentUser = { (_: BriarAPI_GetCurrentUserRequest) -> ResponseMessage<BriarAPI_GetCurrentUserResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateAccountProfile()`.
    public var mockAsyncUpdateAccountProfile = { (_: BriarAPI_UpdateAccountProfileRequest) -> ResponseMessage<BriarAPI_UpdateAccountProfileResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `deleteAccount()`.
    public var mockAsyncDeleteAccount = { (_: BriarAPI_DeleteAccountRequest) -> ResponseMessage<BriarAPI_DeleteAccountResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `registerMobilePushDevice()`.
    public var mockAsyncRegisterMobilePushDevice = { (_: BriarAPI_RegisterMobilePushDeviceRequest) -> ResponseMessage<BriarAPI_RegisterMobilePushDeviceResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `unregisterMobilePushDevice()`.
    public var mockAsyncUnregisterMobilePushDevice = { (_: BriarAPI_UnregisterMobilePushDeviceRequest) -> ResponseMessage<BriarAPI_UnregisterMobilePushDeviceResponse> in .init(result: .success(.init())) }

    public init() {}

    open func `getCurrentUser`(request: BriarAPI_GetCurrentUserRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetCurrentUserResponse> {
        return self.mockAsyncGetCurrentUser(request)
    }

    open func `updateAccountProfile`(request: BriarAPI_UpdateAccountProfileRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateAccountProfileResponse> {
        return self.mockAsyncUpdateAccountProfile(request)
    }

    open func `deleteAccount`(request: BriarAPI_DeleteAccountRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteAccountResponse> {
        return self.mockAsyncDeleteAccount(request)
    }

    open func `registerMobilePushDevice`(request: BriarAPI_RegisterMobilePushDeviceRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_RegisterMobilePushDeviceResponse> {
        return self.mockAsyncRegisterMobilePushDevice(request)
    }

    open func `unregisterMobilePushDevice`(request: BriarAPI_UnregisterMobilePushDeviceRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UnregisterMobilePushDeviceResponse> {
        return self.mockAsyncUnregisterMobilePushDevice(request)
    }
}
