// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/agent.proto
//

import BriarContracts
import Connect
import ConnectMocks
import Foundation
import SwiftProtobuf

/// Mock implementation of `BriarAPI_AgentServiceClientInterface`.
///
/// Production implementations can be substituted with instances of this
/// class to mock RPC calls. Behavior can be customized
/// either through the properties on this class or by
/// subclassing the mock and overriding its methods.
///
/// Note: This class does not handle thread-safe locking, but provides
/// `@unchecked Sendable` conformance to simplify testing and mocking.
@available(iOS 13, *)
open class BriarAPI_AgentServiceClientMock: BriarAPI_AgentServiceClientInterface, @unchecked Sendable {
    /// Mocked for async calls to `listOrganizationAgents()`.
    public var mockAsyncListOrganizationAgents = { (_: BriarAPI_ListOrganizationAgentsRequest) -> ResponseMessage<BriarAPI_ListOrganizationAgentsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `listProjectAgents()`.
    public var mockAsyncListProjectAgents = { (_: BriarAPI_ListProjectAgentsRequest) -> ResponseMessage<BriarAPI_ListProjectAgentsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `listProjectAgentSessions()`.
    public var mockAsyncListProjectAgentSessions = { (_: BriarAPI_ListProjectAgentSessionsRequest) -> ResponseMessage<BriarAPI_ListProjectAgentSessionsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `syncProjectAgentSessions()`.
    public var mockAsyncSyncProjectAgentSessions = { (_: BriarAPI_SyncProjectAgentSessionsRequest) -> ResponseMessage<BriarAPI_SyncProjectAgentSessionsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `getProjectAgentSession()`.
    public var mockAsyncGetProjectAgentSession = { (_: BriarAPI_GetProjectAgentSessionRequest) -> ResponseMessage<BriarAPI_GetProjectAgentSessionResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `putProjectAgentSession()`.
    public var mockAsyncPutProjectAgentSession = { (_: BriarAPI_PutProjectAgentSessionRequest) -> ResponseMessage<BriarAPI_PutProjectAgentSessionResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `runProjectAgentTask()`.
    public var mockAsyncRunProjectAgentTask = { (_: BriarAPI_RunProjectAgentTaskRequest) -> ResponseMessage<BriarAPI_RunProjectAgentTaskResponse> in .init(result: .success(.init())) }

    public init() {}

    open func `listOrganizationAgents`(request: BriarAPI_ListOrganizationAgentsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListOrganizationAgentsResponse> {
        return self.mockAsyncListOrganizationAgents(request)
    }

    open func `listProjectAgents`(request: BriarAPI_ListProjectAgentsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListProjectAgentsResponse> {
        return self.mockAsyncListProjectAgents(request)
    }

    open func `listProjectAgentSessions`(request: BriarAPI_ListProjectAgentSessionsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListProjectAgentSessionsResponse> {
        return self.mockAsyncListProjectAgentSessions(request)
    }

    open func `syncProjectAgentSessions`(request: BriarAPI_SyncProjectAgentSessionsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_SyncProjectAgentSessionsResponse> {
        return self.mockAsyncSyncProjectAgentSessions(request)
    }

    open func `getProjectAgentSession`(request: BriarAPI_GetProjectAgentSessionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetProjectAgentSessionResponse> {
        return self.mockAsyncGetProjectAgentSession(request)
    }

    open func `putProjectAgentSession`(request: BriarAPI_PutProjectAgentSessionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_PutProjectAgentSessionResponse> {
        return self.mockAsyncPutProjectAgentSession(request)
    }

    open func `runProjectAgentTask`(request: BriarAPI_RunProjectAgentTaskRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_RunProjectAgentTaskResponse> {
        return self.mockAsyncRunProjectAgentTask(request)
    }
}
