// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/dm_memory.proto
//

import BriarContracts
import Connect
import Foundation
import SwiftProtobuf

/// Mock implementation of `BriarAPI_DmMemoryServiceClientInterface`.
///
/// Production implementations can be substituted with instances of this
/// class to mock RPC calls. Behavior can be customized
/// either through the properties on this class or by
/// subclassing the mock and overriding its methods.
///
/// Note: This class does not handle thread-safe locking, but provides
/// `@unchecked Sendable` conformance to simplify testing and mocking.
@available(iOS 13, *)
open class BriarAPI_DmMemoryServiceClientMock: BriarAPI_DmMemoryServiceClientInterface, @unchecked Sendable {
    /// Mocked for async calls to `listDmMemories()`.
    public var mockAsyncListDmMemories = { (_: BriarAPI_ListDmMemoriesRequest) -> ResponseMessage<BriarAPI_ListDmMemoriesResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `getDmMemoryDocument()`.
    public var mockAsyncGetDmMemoryDocument = { (_: BriarAPI_GetDmMemoryDocumentRequest) -> ResponseMessage<BriarAPI_GetDmMemoryDocumentResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `listDmMemoryRevisions()`.
    public var mockAsyncListDmMemoryRevisions = { (_: BriarAPI_ListDmMemoryRevisionsRequest) -> ResponseMessage<BriarAPI_ListDmMemoryRevisionsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `createDmMemoryDocument()`.
    public var mockAsyncCreateDmMemoryDocument = { (_: BriarAPI_CreateDmMemoryDocumentRequest) -> ResponseMessage<BriarAPI_CreateDmMemoryDocumentResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateDmMemoryDocument()`.
    public var mockAsyncUpdateDmMemoryDocument = { (_: BriarAPI_UpdateDmMemoryDocumentRequest) -> ResponseMessage<BriarAPI_UpdateDmMemoryDocumentResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `deleteDmMemoryDocument()`.
    public var mockAsyncDeleteDmMemoryDocument = { (_: BriarAPI_DeleteDmMemoryDocumentRequest) -> ResponseMessage<BriarAPI_DeleteDmMemoryDocumentResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateDmMemorySettings()`.
    public var mockAsyncUpdateDmMemorySettings = { (_: BriarAPI_UpdateDmMemorySettingsRequest) -> ResponseMessage<BriarAPI_UpdateDmMemorySettingsResponse> in .init(result: .success(.init())) }

    public init() {}

    open func `listDmMemories`(request: BriarAPI_ListDmMemoriesRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListDmMemoriesResponse> {
        return self.mockAsyncListDmMemories(request)
    }

    open func `getDmMemoryDocument`(request: BriarAPI_GetDmMemoryDocumentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetDmMemoryDocumentResponse> {
        return self.mockAsyncGetDmMemoryDocument(request)
    }

    open func `listDmMemoryRevisions`(request: BriarAPI_ListDmMemoryRevisionsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListDmMemoryRevisionsResponse> {
        return self.mockAsyncListDmMemoryRevisions(request)
    }

    open func `createDmMemoryDocument`(request: BriarAPI_CreateDmMemoryDocumentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateDmMemoryDocumentResponse> {
        return self.mockAsyncCreateDmMemoryDocument(request)
    }

    open func `updateDmMemoryDocument`(request: BriarAPI_UpdateDmMemoryDocumentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateDmMemoryDocumentResponse> {
        return self.mockAsyncUpdateDmMemoryDocument(request)
    }

    open func `deleteDmMemoryDocument`(request: BriarAPI_DeleteDmMemoryDocumentRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteDmMemoryDocumentResponse> {
        return self.mockAsyncDeleteDmMemoryDocument(request)
    }

    open func `updateDmMemorySettings`(request: BriarAPI_UpdateDmMemorySettingsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateDmMemorySettingsResponse> {
        return self.mockAsyncUpdateDmMemorySettings(request)
    }
}
