// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/github.proto
//

import BriarContracts
import Connect
import ConnectMocks
import Foundation
import SwiftProtobuf

/// Mock implementation of `BriarAPI_GitHubIntegrationServiceClientInterface`.
///
/// Production implementations can be substituted with instances of this
/// class to mock RPC calls. Behavior can be customized
/// either through the properties on this class or by
/// subclassing the mock and overriding its methods.
///
/// Note: This class does not handle thread-safe locking, but provides
/// `@unchecked Sendable` conformance to simplify testing and mocking.
@available(iOS 13, *)
open class BriarAPI_GitHubIntegrationServiceClientMock: BriarAPI_GitHubIntegrationServiceClientInterface, @unchecked Sendable {
    /// Mocked for async calls to `getGitHubIntegration()`.
    public var mockAsyncGetGitHubIntegration = { (_: BriarAPI_GetGitHubIntegrationRequest) -> ResponseMessage<BriarAPI_GetGitHubIntegrationResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `beginGitHubInstallation()`.
    public var mockAsyncBeginGitHubInstallation = { (_: BriarAPI_BeginGitHubInstallationRequest) -> ResponseMessage<BriarAPI_BeginGitHubInstallationResponse> in .init(result: .success(.init())) }

    public init() {}

    open func `getGitHubIntegration`(request: BriarAPI_GetGitHubIntegrationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetGitHubIntegrationResponse> {
        return self.mockAsyncGetGitHubIntegration(request)
    }

    open func `beginGitHubInstallation`(request: BriarAPI_BeginGitHubInstallationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_BeginGitHubInstallationResponse> {
        return self.mockAsyncBeginGitHubInstallation(request)
    }
}

/// Mock implementation of `BriarAPI_ProjectGitHubServiceClientInterface`.
///
/// Production implementations can be substituted with instances of this
/// class to mock RPC calls. Behavior can be customized
/// either through the properties on this class or by
/// subclassing the mock and overriding its methods.
///
/// Note: This class does not handle thread-safe locking, but provides
/// `@unchecked Sendable` conformance to simplify testing and mocking.
@available(iOS 13, *)
open class BriarAPI_ProjectGitHubServiceClientMock: BriarAPI_ProjectGitHubServiceClientInterface, @unchecked Sendable {
    /// Mocked for async calls to `createProjectGitHubCredential()`.
    public var mockAsyncCreateProjectGitHubCredential = { (_: BriarAPI_CreateProjectGitHubCredentialRequest) -> ResponseMessage<BriarAPI_CreateProjectGitHubCredentialResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `getProjectGitHubRepository()`.
    public var mockAsyncGetProjectGitHubRepository = { (_: BriarAPI_GetProjectGitHubRepositoryRequest) -> ResponseMessage<BriarAPI_GetProjectGitHubRepositoryResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `createGitHubPullRequest()`.
    public var mockAsyncCreateGitHubPullRequest = { (_: BriarAPI_CreateGitHubPullRequestRequest) -> ResponseMessage<BriarAPI_CreateGitHubPullRequestResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `getGitHubPullRequest()`.
    public var mockAsyncGetGitHubPullRequest = { (_: BriarAPI_GetGitHubPullRequestRequest) -> ResponseMessage<BriarAPI_GetGitHubPullRequestResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateGitHubPullRequest()`.
    public var mockAsyncUpdateGitHubPullRequest = { (_: BriarAPI_UpdateGitHubPullRequestRequest) -> ResponseMessage<BriarAPI_UpdateGitHubPullRequestResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `mergeGitHubPullRequest()`.
    public var mockAsyncMergeGitHubPullRequest = { (_: BriarAPI_MergeGitHubPullRequestRequest) -> ResponseMessage<BriarAPI_MergeGitHubPullRequestResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `createGitHubCommitStatus()`.
    public var mockAsyncCreateGitHubCommitStatus = { (_: BriarAPI_CreateGitHubCommitStatusRequest) -> ResponseMessage<BriarAPI_CreateGitHubCommitStatusResponse> in .init(result: .success(.init())) }

    public init() {}

    open func `createProjectGitHubCredential`(request: BriarAPI_CreateProjectGitHubCredentialRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateProjectGitHubCredentialResponse> {
        return self.mockAsyncCreateProjectGitHubCredential(request)
    }

    open func `getProjectGitHubRepository`(request: BriarAPI_GetProjectGitHubRepositoryRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetProjectGitHubRepositoryResponse> {
        return self.mockAsyncGetProjectGitHubRepository(request)
    }

    open func `createGitHubPullRequest`(request: BriarAPI_CreateGitHubPullRequestRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateGitHubPullRequestResponse> {
        return self.mockAsyncCreateGitHubPullRequest(request)
    }

    open func `getGitHubPullRequest`(request: BriarAPI_GetGitHubPullRequestRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetGitHubPullRequestResponse> {
        return self.mockAsyncGetGitHubPullRequest(request)
    }

    open func `updateGitHubPullRequest`(request: BriarAPI_UpdateGitHubPullRequestRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateGitHubPullRequestResponse> {
        return self.mockAsyncUpdateGitHubPullRequest(request)
    }

    open func `mergeGitHubPullRequest`(request: BriarAPI_MergeGitHubPullRequestRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_MergeGitHubPullRequestResponse> {
        return self.mockAsyncMergeGitHubPullRequest(request)
    }

    open func `createGitHubCommitStatus`(request: BriarAPI_CreateGitHubCommitStatusRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateGitHubCommitStatusResponse> {
        return self.mockAsyncCreateGitHubCommitStatus(request)
    }
}
