// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/issue.proto
//

import BriarContracts
import Connect
import Foundation
import SwiftProtobuf

/// Mock implementation of `BriarAPI_IssueServiceClientInterface`.
///
/// Production implementations can be substituted with instances of this
/// class to mock RPC calls. Behavior can be customized
/// either through the properties on this class or by
/// subclassing the mock and overriding its methods.
///
/// Note: This class does not handle thread-safe locking, but provides
/// `@unchecked Sendable` conformance to simplify testing and mocking.
@available(iOS 13, *)
open class BriarAPI_IssueServiceClientMock: BriarAPI_IssueServiceClientInterface, @unchecked Sendable {
    /// Mocked for async calls to `prepareCreateIssueAttachments()`.
    public var mockAsyncPrepareCreateIssueAttachments = { (_: BriarAPI_PrepareCreateIssueAttachmentsRequest) -> ResponseMessage<BriarAPI_PrepareIssueAttachmentsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `createIssue()`.
    public var mockAsyncCreateIssue = { (_: BriarAPI_CreateIssueRequest) -> ResponseMessage<BriarAPI_CreateIssueResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `prepareUpdateIssueAttachments()`.
    public var mockAsyncPrepareUpdateIssueAttachments = { (_: BriarAPI_PrepareUpdateIssueAttachmentsRequest) -> ResponseMessage<BriarAPI_PrepareIssueAttachmentsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateIssue()`.
    public var mockAsyncUpdateIssue = { (_: BriarAPI_UpdateIssueRequest) -> ResponseMessage<BriarAPI_UpdateIssueResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `deleteIssue()`.
    public var mockAsyncDeleteIssue = { (_: BriarAPI_DeleteIssueRequest) -> ResponseMessage<BriarAPI_DeleteIssueResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `transferIssue()`.
    public var mockAsyncTransferIssue = { (_: BriarAPI_TransferIssueRequest) -> ResponseMessage<BriarAPI_TransferIssueResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `setIssueSubscription()`.
    public var mockAsyncSetIssueSubscription = { (_: BriarAPI_SetIssueSubscriptionRequest) -> ResponseMessage<BriarAPI_SetIssueSubscriptionResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateIssuePreferences()`.
    public var mockAsyncUpdateIssuePreferences = { (_: BriarAPI_UpdateIssuePreferencesRequest) -> ResponseMessage<BriarAPI_UpdateIssuePreferencesResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateIssueCheckpoints()`.
    public var mockAsyncUpdateIssueCheckpoints = { (_: BriarAPI_UpdateIssueCheckpointsRequest) -> ResponseMessage<BriarAPI_UpdateIssueCheckpointsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `setIssueDependency()`.
    public var mockAsyncSetIssueDependency = { (_: BriarAPI_SetIssueDependencyRequest) -> ResponseMessage<BriarAPI_SetIssueDependencyResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `moveRun()`.
    public var mockAsyncMoveRun = { (_: BriarAPI_MoveRunRequest) -> ResponseMessage<BriarAPI_MoveRunResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `retryRun()`.
    public var mockAsyncRetryRun = { (_: BriarAPI_RetryRunRequest) -> ResponseMessage<BriarAPI_RetryRunResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `cancelRun()`.
    public var mockAsyncCancelRun = { (_: BriarAPI_CancelRunRequest) -> ResponseMessage<BriarAPI_CancelRunResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `resumeRun()`.
    public var mockAsyncResumeRun = { (_: BriarAPI_ResumeRunRequest) -> ResponseMessage<BriarAPI_ResumeRunResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `reworkRun()`.
    public var mockAsyncReworkRun = { (_: BriarAPI_ReworkRunRequest) -> ResponseMessage<BriarAPI_ReworkRunResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `unassignRun()`.
    public var mockAsyncUnassignRun = { (_: BriarAPI_UnassignRunRequest) -> ResponseMessage<BriarAPI_UnassignRunResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `dispatchRun()`.
    public var mockAsyncDispatchRun = { (_: BriarAPI_DispatchRunRequest) -> ResponseMessage<BriarAPI_DispatchRunResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `reassignRun()`.
    public var mockAsyncReassignRun = { (_: BriarAPI_ReassignRunRequest) -> ResponseMessage<BriarAPI_ReassignRunResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `completeResultReview()`.
    public var mockAsyncCompleteResultReview = { (_: BriarAPI_CompleteResultReviewRequest) -> ResponseMessage<BriarAPI_CompleteResultReviewResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `listIssueMessages()`.
    public var mockAsyncListIssueMessages = { (_: BriarAPI_ListIssueMessagesRequest) -> ResponseMessage<BriarAPI_ListIssueMessagesResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `syncIssueMessages()`.
    public var mockAsyncSyncIssueMessages = { (_: BriarAPI_SyncIssueMessagesRequest) -> ResponseMessage<BriarAPI_SyncIssueMessagesResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `prepareIssueMessageAttachments()`.
    public var mockAsyncPrepareIssueMessageAttachments = { (_: BriarAPI_PrepareIssueMessageAttachmentsRequest) -> ResponseMessage<BriarAPI_PrepareIssueAttachmentsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `createIssueMessage()`.
    public var mockAsyncCreateIssueMessage = { (_: BriarAPI_CreateIssueMessageRequest) -> ResponseMessage<BriarAPI_CreateIssueMessageResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateIssueMessage()`.
    public var mockAsyncUpdateIssueMessage = { (_: BriarAPI_UpdateIssueMessageRequest) -> ResponseMessage<BriarAPI_UpdateIssueMessageResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `deleteIssueMessage()`.
    public var mockAsyncDeleteIssueMessage = { (_: BriarAPI_DeleteIssueMessageRequest) -> ResponseMessage<BriarAPI_DeleteIssueMessageResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `getIssueAgentReply()`.
    public var mockAsyncGetIssueAgentReply = { (_: BriarAPI_GetIssueAgentReplyRequest) -> ResponseMessage<BriarAPI_GetIssueAgentReplyResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `listRunEvidence()`.
    public var mockAsyncListRunEvidence = { (_: BriarAPI_ListRunEvidenceRequest) -> ResponseMessage<BriarAPI_ListRunEvidenceResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `acceptIssueReworkProposal()`.
    public var mockAsyncAcceptIssueReworkProposal = { (_: BriarAPI_AcceptIssueReworkProposalRequest) -> ResponseMessage<BriarAPI_AcceptIssueReworkProposalResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `acceptIssueActionProposal()`.
    public var mockAsyncAcceptIssueActionProposal = { (_: BriarAPI_AcceptIssueActionProposalRequest) -> ResponseMessage<BriarAPI_AcceptIssueActionProposalResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `acceptIssueExecutionProposal()`.
    public var mockAsyncAcceptIssueExecutionProposal = { (_: BriarAPI_AcceptIssueExecutionProposalRequest) -> ResponseMessage<BriarAPI_AcceptIssueExecutionProposalResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `acceptIssueSkillExecutionProposal()`.
    public var mockAsyncAcceptIssueSkillExecutionProposal = { (_: BriarAPI_AcceptIssueSkillExecutionProposalRequest) -> ResponseMessage<BriarAPI_AcceptIssueSkillExecutionProposalResponse> in .init(result: .success(.init())) }

    public init() {}

    open func `prepareCreateIssueAttachments`(request: BriarAPI_PrepareCreateIssueAttachmentsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_PrepareIssueAttachmentsResponse> {
        return self.mockAsyncPrepareCreateIssueAttachments(request)
    }

    open func `createIssue`(request: BriarAPI_CreateIssueRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateIssueResponse> {
        return self.mockAsyncCreateIssue(request)
    }

    open func `prepareUpdateIssueAttachments`(request: BriarAPI_PrepareUpdateIssueAttachmentsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_PrepareIssueAttachmentsResponse> {
        return self.mockAsyncPrepareUpdateIssueAttachments(request)
    }

    open func `updateIssue`(request: BriarAPI_UpdateIssueRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateIssueResponse> {
        return self.mockAsyncUpdateIssue(request)
    }

    open func `deleteIssue`(request: BriarAPI_DeleteIssueRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteIssueResponse> {
        return self.mockAsyncDeleteIssue(request)
    }

    open func `transferIssue`(request: BriarAPI_TransferIssueRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_TransferIssueResponse> {
        return self.mockAsyncTransferIssue(request)
    }

    open func `setIssueSubscription`(request: BriarAPI_SetIssueSubscriptionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_SetIssueSubscriptionResponse> {
        return self.mockAsyncSetIssueSubscription(request)
    }

    open func `updateIssuePreferences`(request: BriarAPI_UpdateIssuePreferencesRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateIssuePreferencesResponse> {
        return self.mockAsyncUpdateIssuePreferences(request)
    }

    open func `updateIssueCheckpoints`(request: BriarAPI_UpdateIssueCheckpointsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateIssueCheckpointsResponse> {
        return self.mockAsyncUpdateIssueCheckpoints(request)
    }

    open func `setIssueDependency`(request: BriarAPI_SetIssueDependencyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_SetIssueDependencyResponse> {
        return self.mockAsyncSetIssueDependency(request)
    }

    open func `moveRun`(request: BriarAPI_MoveRunRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_MoveRunResponse> {
        return self.mockAsyncMoveRun(request)
    }

    open func `retryRun`(request: BriarAPI_RetryRunRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_RetryRunResponse> {
        return self.mockAsyncRetryRun(request)
    }

    open func `cancelRun`(request: BriarAPI_CancelRunRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CancelRunResponse> {
        return self.mockAsyncCancelRun(request)
    }

    open func `resumeRun`(request: BriarAPI_ResumeRunRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ResumeRunResponse> {
        return self.mockAsyncResumeRun(request)
    }

    open func `reworkRun`(request: BriarAPI_ReworkRunRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ReworkRunResponse> {
        return self.mockAsyncReworkRun(request)
    }

    open func `unassignRun`(request: BriarAPI_UnassignRunRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UnassignRunResponse> {
        return self.mockAsyncUnassignRun(request)
    }

    open func `dispatchRun`(request: BriarAPI_DispatchRunRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DispatchRunResponse> {
        return self.mockAsyncDispatchRun(request)
    }

    open func `reassignRun`(request: BriarAPI_ReassignRunRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ReassignRunResponse> {
        return self.mockAsyncReassignRun(request)
    }

    open func `completeResultReview`(request: BriarAPI_CompleteResultReviewRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CompleteResultReviewResponse> {
        return self.mockAsyncCompleteResultReview(request)
    }

    open func `listIssueMessages`(request: BriarAPI_ListIssueMessagesRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListIssueMessagesResponse> {
        return self.mockAsyncListIssueMessages(request)
    }

    open func `syncIssueMessages`(request: BriarAPI_SyncIssueMessagesRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_SyncIssueMessagesResponse> {
        return self.mockAsyncSyncIssueMessages(request)
    }

    open func `prepareIssueMessageAttachments`(request: BriarAPI_PrepareIssueMessageAttachmentsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_PrepareIssueAttachmentsResponse> {
        return self.mockAsyncPrepareIssueMessageAttachments(request)
    }

    open func `createIssueMessage`(request: BriarAPI_CreateIssueMessageRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateIssueMessageResponse> {
        return self.mockAsyncCreateIssueMessage(request)
    }

    open func `updateIssueMessage`(request: BriarAPI_UpdateIssueMessageRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateIssueMessageResponse> {
        return self.mockAsyncUpdateIssueMessage(request)
    }

    open func `deleteIssueMessage`(request: BriarAPI_DeleteIssueMessageRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteIssueMessageResponse> {
        return self.mockAsyncDeleteIssueMessage(request)
    }

    open func `getIssueAgentReply`(request: BriarAPI_GetIssueAgentReplyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetIssueAgentReplyResponse> {
        return self.mockAsyncGetIssueAgentReply(request)
    }

    open func `listRunEvidence`(request: BriarAPI_ListRunEvidenceRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListRunEvidenceResponse> {
        return self.mockAsyncListRunEvidence(request)
    }

    open func `acceptIssueReworkProposal`(request: BriarAPI_AcceptIssueReworkProposalRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_AcceptIssueReworkProposalResponse> {
        return self.mockAsyncAcceptIssueReworkProposal(request)
    }

    open func `acceptIssueActionProposal`(request: BriarAPI_AcceptIssueActionProposalRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_AcceptIssueActionProposalResponse> {
        return self.mockAsyncAcceptIssueActionProposal(request)
    }

    open func `acceptIssueExecutionProposal`(request: BriarAPI_AcceptIssueExecutionProposalRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_AcceptIssueExecutionProposalResponse> {
        return self.mockAsyncAcceptIssueExecutionProposal(request)
    }

    open func `acceptIssueSkillExecutionProposal`(request: BriarAPI_AcceptIssueSkillExecutionProposalRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_AcceptIssueSkillExecutionProposalResponse> {
        return self.mockAsyncAcceptIssueSkillExecutionProposal(request)
    }
}
