// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/merge_queue.proto
//

import BriarContracts
import Connect
import Foundation
import SwiftProtobuf

/// Mock implementation of `BriarAPI_MergeQueueServiceClientInterface`.
///
/// Production implementations can be substituted with instances of this
/// class to mock RPC calls. Behavior can be customized
/// either through the properties on this class or by
/// subclassing the mock and overriding its methods.
///
/// Note: This class does not handle thread-safe locking, but provides
/// `@unchecked Sendable` conformance to simplify testing and mocking.
@available(iOS 13, *)
open class BriarAPI_MergeQueueServiceClientMock: BriarAPI_MergeQueueServiceClientInterface, @unchecked Sendable {
    /// Mocked for async calls to `getMergeQueueProfile()`.
    public var mockAsyncGetMergeQueueProfile = { (_: BriarAPI_GetMergeQueueProfileRequest) -> ResponseMessage<BriarAPI_GetMergeQueueProfileResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateMergeQueueProfile()`.
    public var mockAsyncUpdateMergeQueueProfile = { (_: BriarAPI_UpdateMergeQueueProfileRequest) -> ResponseMessage<BriarAPI_UpdateMergeQueueProfileResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `getMergeQueueStatus()`.
    public var mockAsyncGetMergeQueueStatus = { (_: BriarAPI_GetMergeQueueStatusRequest) -> ResponseMessage<BriarAPI_GetMergeQueueStatusResponse> in .init(result: .success(.init())) }

    public init() {}

    open func `getMergeQueueProfile`(request: BriarAPI_GetMergeQueueProfileRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetMergeQueueProfileResponse> {
        return self.mockAsyncGetMergeQueueProfile(request)
    }

    open func `updateMergeQueueProfile`(request: BriarAPI_UpdateMergeQueueProfileRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateMergeQueueProfileResponse> {
        return self.mockAsyncUpdateMergeQueueProfile(request)
    }

    open func `getMergeQueueStatus`(request: BriarAPI_GetMergeQueueStatusRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetMergeQueueStatusResponse> {
        return self.mockAsyncGetMergeQueueStatus(request)
    }
}
