// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/project.proto
//

import BriarContracts
import Connect
import Foundation
import SwiftProtobuf

/// Mock implementation of `BriarAPI_ProjectServiceClientInterface`.
///
/// Production implementations can be substituted with instances of this
/// class to mock RPC calls. Behavior can be customized
/// either through the properties on this class or by
/// subclassing the mock and overriding its methods.
///
/// Note: This class does not handle thread-safe locking, but provides
/// `@unchecked Sendable` conformance to simplify testing and mocking.
@available(iOS 13, *)
open class BriarAPI_ProjectServiceClientMock: BriarAPI_ProjectServiceClientInterface, @unchecked Sendable {
    /// Mocked for async calls to `listProjects()`.
    public var mockAsyncListProjects = { (_: BriarAPI_ListProjectsRequest) -> ResponseMessage<BriarAPI_ListProjectsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `createProject()`.
    public var mockAsyncCreateProject = { (_: BriarAPI_CreateProjectRequest) -> ResponseMessage<BriarAPI_CreateProjectResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `deleteProject()`.
    public var mockAsyncDeleteProject = { (_: BriarAPI_DeleteProjectRequest) -> ResponseMessage<BriarAPI_DeleteProjectResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateProjectIcon()`.
    public var mockAsyncUpdateProjectIcon = { (_: BriarAPI_UpdateProjectIconRequest) -> ResponseMessage<BriarAPI_UpdateProjectIconResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateProjectIssueKeyPrefix()`.
    public var mockAsyncUpdateProjectIssueKeyPrefix = { (_: BriarAPI_UpdateProjectIssueKeyPrefixRequest) -> ResponseMessage<BriarAPI_UpdateProjectIssueKeyPrefixResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateProjectTabs()`.
    public var mockAsyncUpdateProjectTabs = { (_: BriarAPI_UpdateProjectTabsRequest) -> ResponseMessage<BriarAPI_UpdateProjectTabsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `createProjectAgentToken()`.
    public var mockAsyncCreateProjectAgentToken = { (_: BriarAPI_CreateProjectAgentTokenRequest) -> ResponseMessage<BriarAPI_CreateProjectAgentTokenResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateProjectSettings()`.
    public var mockAsyncUpdateProjectSettings = { (_: BriarAPI_UpdateProjectSettingsRequest) -> ResponseMessage<BriarAPI_UpdateProjectSettingsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateCheckpointPolicy()`.
    public var mockAsyncUpdateCheckpointPolicy = { (_: BriarAPI_UpdateCheckpointPolicyRequest) -> ResponseMessage<BriarAPI_UpdateCheckpointPolicyResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `getProjectExecutionWorkerPolicy()`.
    public var mockAsyncGetProjectExecutionWorkerPolicy = { (_: BriarAPI_GetProjectExecutionWorkerPolicyRequest) -> ResponseMessage<BriarAPI_GetProjectExecutionWorkerPolicyResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateProjectExecutionWorkerPolicy()`.
    public var mockAsyncUpdateProjectExecutionWorkerPolicy = { (_: BriarAPI_UpdateProjectExecutionWorkerPolicyRequest) -> ResponseMessage<BriarAPI_UpdateProjectExecutionWorkerPolicyResponse> in .init(result: .success(.init())) }

    public init() {}

    open func `listProjects`(request: BriarAPI_ListProjectsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListProjectsResponse> {
        return self.mockAsyncListProjects(request)
    }

    open func `createProject`(request: BriarAPI_CreateProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateProjectResponse> {
        return self.mockAsyncCreateProject(request)
    }

    open func `deleteProject`(request: BriarAPI_DeleteProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteProjectResponse> {
        return self.mockAsyncDeleteProject(request)
    }

    open func `updateProjectIcon`(request: BriarAPI_UpdateProjectIconRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateProjectIconResponse> {
        return self.mockAsyncUpdateProjectIcon(request)
    }

    open func `updateProjectIssueKeyPrefix`(request: BriarAPI_UpdateProjectIssueKeyPrefixRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateProjectIssueKeyPrefixResponse> {
        return self.mockAsyncUpdateProjectIssueKeyPrefix(request)
    }

    open func `updateProjectTabs`(request: BriarAPI_UpdateProjectTabsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateProjectTabsResponse> {
        return self.mockAsyncUpdateProjectTabs(request)
    }

    open func `createProjectAgentToken`(request: BriarAPI_CreateProjectAgentTokenRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateProjectAgentTokenResponse> {
        return self.mockAsyncCreateProjectAgentToken(request)
    }

    open func `updateProjectSettings`(request: BriarAPI_UpdateProjectSettingsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateProjectSettingsResponse> {
        return self.mockAsyncUpdateProjectSettings(request)
    }

    open func `updateCheckpointPolicy`(request: BriarAPI_UpdateCheckpointPolicyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateCheckpointPolicyResponse> {
        return self.mockAsyncUpdateCheckpointPolicy(request)
    }

    open func `getProjectExecutionWorkerPolicy`(request: BriarAPI_GetProjectExecutionWorkerPolicyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetProjectExecutionWorkerPolicyResponse> {
        return self.mockAsyncGetProjectExecutionWorkerPolicy(request)
    }

    open func `updateProjectExecutionWorkerPolicy`(request: BriarAPI_UpdateProjectExecutionWorkerPolicyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateProjectExecutionWorkerPolicyResponse> {
        return self.mockAsyncUpdateProjectExecutionWorkerPolicy(request)
    }
}
