// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/realtime_control.proto
//

import BriarContracts
import Connect
import Foundation
import SwiftProtobuf

/// Mock implementation of `BriarAPI_RealtimeServiceClientInterface`.
///
/// Production implementations can be substituted with instances of this
/// class to mock RPC calls. Behavior can be customized
/// either through the properties on this class or by
/// subclassing the mock and overriding its methods.
///
/// Note: This class does not handle thread-safe locking, but provides
/// `@unchecked Sendable` conformance to simplify testing and mocking.
@available(iOS 13, *)
open class BriarAPI_RealtimeServiceClientMock: BriarAPI_RealtimeServiceClientInterface, @unchecked Sendable {
    /// Mocked for async calls to `createRealtimeTicket()`.
    public var mockAsyncCreateRealtimeTicket = { (_: BriarAPI_CreateRealtimeTicketRequest) -> ResponseMessage<BriarAPI_CreateRealtimeTicketResponse> in .init(result: .success(.init())) }

    public init() {}

    open func `createRealtimeTicket`(request: BriarAPI_CreateRealtimeTicketRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateRealtimeTicketResponse> {
        return self.mockAsyncCreateRealtimeTicket(request)
    }
}
