// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: briar/app/v1/team.proto
//

import BriarContracts
import Connect
import Foundation
import SwiftProtobuf

/// Mock implementation of `BriarAPI_TeamServiceClientInterface`.
///
/// Production implementations can be substituted with instances of this
/// class to mock RPC calls. Behavior can be customized
/// either through the properties on this class or by
/// subclassing the mock and overriding its methods.
///
/// Note: This class does not handle thread-safe locking, but provides
/// `@unchecked Sendable` conformance to simplify testing and mocking.
@available(iOS 13, *)
open class BriarAPI_TeamServiceClientMock: BriarAPI_TeamServiceClientInterface, @unchecked Sendable {
    /// Mocked for async calls to `listTeams()`.
    public var mockAsyncListTeams = { (_: BriarAPI_ListTeamsRequest) -> ResponseMessage<BriarAPI_ListTeamsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `createTeam()`.
    public var mockAsyncCreateTeam = { (_: BriarAPI_CreateTeamRequest) -> ResponseMessage<BriarAPI_CreateTeamResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `deleteTeam()`.
    public var mockAsyncDeleteTeam = { (_: BriarAPI_DeleteTeamRequest) -> ResponseMessage<BriarAPI_DeleteTeamResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateTeamIcon()`.
    public var mockAsyncUpdateTeamIcon = { (_: BriarAPI_UpdateTeamIconRequest) -> ResponseMessage<BriarAPI_UpdateTeamIconResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateTeamIssueKeyPrefix()`.
    public var mockAsyncUpdateTeamIssueKeyPrefix = { (_: BriarAPI_UpdateTeamIssueKeyPrefixRequest) -> ResponseMessage<BriarAPI_UpdateTeamIssueKeyPrefixResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateTeamTabs()`.
    public var mockAsyncUpdateTeamTabs = { (_: BriarAPI_UpdateTeamTabsRequest) -> ResponseMessage<BriarAPI_UpdateTeamTabsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `createTeamAgentToken()`.
    public var mockAsyncCreateTeamAgentToken = { (_: BriarAPI_CreateTeamAgentTokenRequest) -> ResponseMessage<BriarAPI_CreateTeamAgentTokenResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateTeamSettings()`.
    public var mockAsyncUpdateTeamSettings = { (_: BriarAPI_UpdateTeamSettingsRequest) -> ResponseMessage<BriarAPI_UpdateTeamSettingsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateCheckpointPolicy()`.
    public var mockAsyncUpdateCheckpointPolicy = { (_: BriarAPI_UpdateCheckpointPolicyRequest) -> ResponseMessage<BriarAPI_UpdateCheckpointPolicyResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `getTeamExecutionWorkerPolicy()`.
    public var mockAsyncGetTeamExecutionWorkerPolicy = { (_: BriarAPI_GetTeamExecutionWorkerPolicyRequest) -> ResponseMessage<BriarAPI_GetTeamExecutionWorkerPolicyResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updateTeamExecutionWorkerPolicy()`.
    public var mockAsyncUpdateTeamExecutionWorkerPolicy = { (_: BriarAPI_UpdateTeamExecutionWorkerPolicyRequest) -> ResponseMessage<BriarAPI_UpdateTeamExecutionWorkerPolicyResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `listTeamPlanningProjects()`.
    public var mockAsyncListTeamPlanningProjects = { (_: BriarAPI_ListTeamPlanningProjectsRequest) -> ResponseMessage<BriarAPI_ListTeamPlanningProjectsResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `createPlanningProject()`.
    public var mockAsyncCreatePlanningProject = { (_: BriarAPI_CreatePlanningProjectRequest) -> ResponseMessage<BriarAPI_CreatePlanningProjectResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `updatePlanningProject()`.
    public var mockAsyncUpdatePlanningProject = { (_: BriarAPI_UpdatePlanningProjectRequest) -> ResponseMessage<BriarAPI_UpdatePlanningProjectResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `deletePlanningProject()`.
    public var mockAsyncDeletePlanningProject = { (_: BriarAPI_DeletePlanningProjectRequest) -> ResponseMessage<BriarAPI_DeletePlanningProjectResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `moveIssueToPlanningProject()`.
    public var mockAsyncMoveIssueToPlanningProject = { (_: BriarAPI_MoveIssueToPlanningProjectRequest) -> ResponseMessage<BriarAPI_MoveIssueToPlanningProjectResponse> in .init(result: .success(.init())) }
    /// Mocked for async calls to `resolveIssueHierarchyLocation()`.
    public var mockAsyncResolveIssueHierarchyLocation = { (_: BriarAPI_ResolveIssueHierarchyLocationRequest) -> ResponseMessage<BriarAPI_ResolveIssueHierarchyLocationResponse> in .init(result: .success(.init())) }

    public init() {}

    open func `listTeams`(request: BriarAPI_ListTeamsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListTeamsResponse> {
        return self.mockAsyncListTeams(request)
    }

    open func `createTeam`(request: BriarAPI_CreateTeamRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateTeamResponse> {
        return self.mockAsyncCreateTeam(request)
    }

    open func `deleteTeam`(request: BriarAPI_DeleteTeamRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeleteTeamResponse> {
        return self.mockAsyncDeleteTeam(request)
    }

    open func `updateTeamIcon`(request: BriarAPI_UpdateTeamIconRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateTeamIconResponse> {
        return self.mockAsyncUpdateTeamIcon(request)
    }

    open func `updateTeamIssueKeyPrefix`(request: BriarAPI_UpdateTeamIssueKeyPrefixRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateTeamIssueKeyPrefixResponse> {
        return self.mockAsyncUpdateTeamIssueKeyPrefix(request)
    }

    open func `updateTeamTabs`(request: BriarAPI_UpdateTeamTabsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateTeamTabsResponse> {
        return self.mockAsyncUpdateTeamTabs(request)
    }

    open func `createTeamAgentToken`(request: BriarAPI_CreateTeamAgentTokenRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreateTeamAgentTokenResponse> {
        return self.mockAsyncCreateTeamAgentToken(request)
    }

    open func `updateTeamSettings`(request: BriarAPI_UpdateTeamSettingsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateTeamSettingsResponse> {
        return self.mockAsyncUpdateTeamSettings(request)
    }

    open func `updateCheckpointPolicy`(request: BriarAPI_UpdateCheckpointPolicyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateCheckpointPolicyResponse> {
        return self.mockAsyncUpdateCheckpointPolicy(request)
    }

    open func `getTeamExecutionWorkerPolicy`(request: BriarAPI_GetTeamExecutionWorkerPolicyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_GetTeamExecutionWorkerPolicyResponse> {
        return self.mockAsyncGetTeamExecutionWorkerPolicy(request)
    }

    open func `updateTeamExecutionWorkerPolicy`(request: BriarAPI_UpdateTeamExecutionWorkerPolicyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdateTeamExecutionWorkerPolicyResponse> {
        return self.mockAsyncUpdateTeamExecutionWorkerPolicy(request)
    }

    open func `listTeamPlanningProjects`(request: BriarAPI_ListTeamPlanningProjectsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ListTeamPlanningProjectsResponse> {
        return self.mockAsyncListTeamPlanningProjects(request)
    }

    open func `createPlanningProject`(request: BriarAPI_CreatePlanningProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_CreatePlanningProjectResponse> {
        return self.mockAsyncCreatePlanningProject(request)
    }

    open func `updatePlanningProject`(request: BriarAPI_UpdatePlanningProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_UpdatePlanningProjectResponse> {
        return self.mockAsyncUpdatePlanningProject(request)
    }

    open func `deletePlanningProject`(request: BriarAPI_DeletePlanningProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_DeletePlanningProjectResponse> {
        return self.mockAsyncDeletePlanningProject(request)
    }

    open func `moveIssueToPlanningProject`(request: BriarAPI_MoveIssueToPlanningProjectRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_MoveIssueToPlanningProjectResponse> {
        return self.mockAsyncMoveIssueToPlanningProject(request)
    }

    open func `resolveIssueHierarchyLocation`(request: BriarAPI_ResolveIssueHierarchyLocationRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<BriarAPI_ResolveIssueHierarchyLocationResponse> {
        return self.mockAsyncResolveIssueHierarchyLocation(request)
    }
}
